using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace SplatHex;
public class Class64 : Form {
    private IDisposable g89;
    private Button U8c;
    private Button F8y;
    public Label B8r;
    public Label j8q;
    public Label u8k;
    public Label B8M;
    public NumericUpDown c8u;
    public Label L8g;
    public CheckBox T82;
    public CheckBox i83;
    public Label H8d;
    public Label y8H;
    public NumericUpDown E84;
    public CheckBox d85;
    public CheckBox y8s;
    public NumericUpDown N8Z;
    private PictureBox z8a;
    private PictureBox G8j;
    private PictureBox k8z;
    private PictureBox DnE;
    public Class64() {
        R8x();
        T82.Checked = (Class108.io2.ptt & 0x10000) != 0;
        y8s.Checked = (Class108.io2.ptt & 0x20000) != 0;
        d85.Checked = (Class108.io2.ptt & 0x40000) != 0;
        i83.Checked = (Class108.io2.ptt & 0x80000) != 0;
        c8u.Value = Class108.io2.BtV;
        E84.Value = Class108.io2.ItO;
        N8Z.Value = Class108.io2.ete;
    }

    private void O8A() {
        uint uint_ = (uint)Class108.io2.ptt;
        Class115.cH2(ref uint_, 65536u, T82.Checked);
        Class115.cH2(ref uint_, 131072u, y8s.Checked);
        Class115.cH2(ref uint_, 262144u, d85.Checked);
        Class115.cH2(ref uint_, 524288u, i83.Checked);
        Class108.io2.ptt = (int)uint_;
        Class108.io2.BtV = (int)c8u.Value;
        Class108.io2.ItO = (int)E84.Value;
        Class108.io2.ete = (int)N8Z.Value;
    }

    private void G8f(object sender, EventArgs e) {
        O8A();
        Close();
    }

    private void U86(object sender, EventArgs e) {
        Close();
    }

    protected override void Dispose(bool disposing) {
        if (disposing && g89 != null) {
            g89.Dispose();
        }

        base.Dispose(disposing);
    }

    private void R8x() {
        U8c = new Button();
        F8y = new Button();
        B8r = new Label();
        j8q = new Label();
        u8k = new Label();
        B8M = new Label();
        c8u = new NumericUpDown();
        L8g = new Label();
        T82 = new CheckBox();
        i83 = new CheckBox();
        H8d = new Label();
        y8H = new Label();
        E84 = new NumericUpDown();
        d85 = new CheckBox();
        y8s = new CheckBox();
        N8Z = new NumericUpDown();
        z8a = new PictureBox();
        G8j = new PictureBox();
        k8z = new PictureBox();
        DnE = new PictureBox();
        ((ISupportInitialize)c8u).BeginInit();
        ((ISupportInitialize)E84).BeginInit();
        ((ISupportInitialize)N8Z).BeginInit();
        ((ISupportInitialize)z8a).BeginInit();
        ((ISupportInitialize)G8j).BeginInit();
        ((ISupportInitialize)k8z).BeginInit();
        ((ISupportInitialize)DnE).BeginInit();
        SuspendLayout();
        U8c.Location = new Point(488, 230);
        U8c.Name = "BTN_Cancel";
        U8c.Size = new Size(59, 23);
        U8c.TabIndex = 42;
        U8c.Text = "Cancel";
        U8c.UseVisualStyleBackColor = true;
        U8c.Click += U86;
        F8y.Location = new Point(423, 230);
        F8y.Name = "BTN_Save";
        F8y.Size = new Size(59, 23);
        F8y.TabIndex = 41;
        F8y.Text = "Save";
        F8y.UseVisualStyleBackColor = true;
        F8y.Click += G8f;
        B8r.AutoSize = true;
        B8r.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold);
        B8r.ForeColor = Color.Fuchsia;
        B8r.Location = new Point(419, 111);
        B8r.Name = "label31";
        B8r.Size = new Size(121, 24);
        B8r.TabIndex = 40;
        B8r.Text = "Squid Beatz";
        j8q.AutoSize = true;
        j8q.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold);
        j8q.ForeColor = Color.Gray;
        j8q.Location = new Point(150, 111);
        j8q.Name = "label30";
        j8q.Size = new Size(125, 24);
        j8q.TabIndex = 39;
        j8q.Text = "Squid Racer";
        u8k.AutoSize = true;
        u8k.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold);
        u8k.ForeColor = Color.FromArgb(128, 128, 255);
        u8k.Location = new Point(411, 10);
        u8k.Name = "label29";
        u8k.Size = new Size(98, 24);
        u8k.TabIndex = 38;
        u8k.Text = "SquidBall";
        B8M.AutoSize = true;
        B8M.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold);
        B8M.ForeColor = Color.FromArgb(255, 128, 0);
        B8M.Location = new Point(146, 10);
        B8M.Name = "label24";
        B8M.Size = new Size(121, 24);
        B8M.TabIndex = 37;
        B8M.Text = "Squid Jump";
        c8u.Location = new Point(151, 48);
        c8u.Maximum = new decimal(new int[4] { 999999999, 0, 0, 0 });
        c8u.Name = "value_squidJumpHigh";
        c8u.Size = new Size(105, 20);
        c8u.TabIndex = 27;
        L8g.AutoSize = true;
        L8g.Location = new Point(147, 135);
        L8g.Name = "label27";
        L8g.Size = new Size(61, 13);
        L8g.TabIndex = 34;
        L8g.Text = "Highscore :";
        T82.AutoSize = true;
        T82.Location = new Point(151, 71);
        T82.Name = "checkbox_squidJump";
        T82.Size = new Size(72, 17);
        T82.TabIndex = 30;
        T82.Text = "Unlocked";
        T82.UseVisualStyleBackColor = true;
        i83.AutoSize = true;
        i83.Location = new Point(415, 173);
        i83.Name = "checkbox_squidBeatz";
        i83.Size = new Size(72, 17);
        i83.TabIndex = 31;
        i83.Text = "Unlocked";
        i83.UseVisualStyleBackColor = true;
        H8d.AutoSize = true;
        H8d.Location = new Point(408, 34);
        H8d.Name = "label23";
        H8d.Size = new Size(61, 13);
        H8d.TabIndex = 35;
        H8d.Text = "Highscore :";
        y8H.AutoSize = true;
        y8H.Location = new Point(148, 33);
        y8H.Name = "label26";
        y8H.Size = new Size(61, 13);
        y8H.TabIndex = 36;
        y8H.Text = "Highscore :";
        E84.Location = new Point(411, 49);
        E84.Maximum = new decimal(new int[4] { 999999999, 0, 0, 0 });
        E84.Name = "value_squidballHigh";
        E84.Size = new Size(105, 20);
        E84.TabIndex = 28;
        d85.AutoSize = true;
        d85.Location = new Point(150, 173);
        d85.Name = "checkbox_squidRacer";
        d85.Size = new Size(72, 17);
        d85.TabIndex = 32;
        d85.Text = "Unlocked";
        d85.UseVisualStyleBackColor = true;
        y8s.AutoSize = true;
        y8s.Location = new Point(411, 72);
        y8s.Name = "checkbox_squidBall";
        y8s.Size = new Size(72, 17);
        y8s.TabIndex = 33;
        y8s.Text = "Unlocked";
        y8s.UseVisualStyleBackColor = true;
        N8Z.Location = new Point(150, 150);
        N8Z.Maximum = new decimal(new int[4] { 999999999, 0, 0, 0 });
        N8Z.Name = "value_squidRacerHigh";
        N8Z.Size = new Size(105, 20);
        N8Z.TabIndex = 29;
        z8a.Image = Resources.MiniGameIcon_00;
        z8a.Location = new Point(12, 12);
        z8a.Name = "pictureBox1";
        z8a.Size = new Size(128, 98);
        z8a.SizeMode = PictureBoxSizeMode.Zoom;
        z8a.TabIndex = 23;
        z8a.TabStop = false;
        G8j.Image = Resources.MiniGameIcon_03;
        G8j.Location = new Point(281, 115);
        G8j.Name = "pictureBox4";
        G8j.Size = new Size(128, 98);
        G8j.SizeMode = PictureBoxSizeMode.Zoom;
        G8j.TabIndex = 26;
        G8j.TabStop = false;
        k8z.Image = Resources.MiniGameIcon_01;
        k8z.Location = new Point(273, 12);
        k8z.Name = "pictureBox2";
        k8z.Size = new Size(128, 98);
        k8z.SizeMode = PictureBoxSizeMode.Zoom;
        k8z.TabIndex = 24;
        k8z.TabStop = false;
        DnE.Image = Resources.MiniGameIcon_02;
        DnE.Location = new Point(12, 116);
        DnE.Name = "pictureBox3";
        DnE.Size = new Size(128, 98);
        DnE.SizeMode = PictureBoxSizeMode.Zoom;
        DnE.TabIndex = 25;
        DnE.TabStop = false;
        base.AutoScaleDimensions = new SizeF(6f, 13f);
        base.AutoScaleMode = AutoScaleMode.Font;
        base.ClientSize = new Size(555, 262);
        base.Controls.Add(U8c);
        base.Controls.Add(F8y);
        base.Controls.Add(z8a);
        base.Controls.Add(B8r);
        base.Controls.Add(DnE);
        base.Controls.Add(j8q);
        base.Controls.Add(k8z);
        base.Controls.Add(u8k);
        base.Controls.Add(G8j);
        base.Controls.Add(B8M);
        base.Controls.Add(N8Z);
        base.Controls.Add(c8u);
        base.Controls.Add(y8s);
        base.Controls.Add(L8g);
        base.Controls.Add(d85);
        base.Controls.Add(T82);
        base.Controls.Add(E84);
        base.Controls.Add(i83);
        base.Controls.Add(y8H);
        base.Controls.Add(H8d);
        base.Name = "MinigameSplat1";
        base.ShowIcon = false;
        base.StartPosition = FormStartPosition.CenterScreen;
        Text = "SplatHeX - Splatoon 1 - Minigame Editor";
        ((ISupportInitialize)c8u).EndInit();
        ((ISupportInitialize)E84).EndInit();
        ((ISupportInitialize)N8Z).EndInit();
        ((ISupportInitialize)z8a).EndInit();
        ((ISupportInitialize)G8j).EndInit();
        ((ISupportInitialize)k8z).EndInit();
        ((ISupportInitialize)DnE).EndInit();
        ResumeLayout(performLayout: false);
        PerformLayout();
    }
}