using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.IO;
using System.Resources;
using System.Text;
using System.Windows.Forms;

namespace SplatHex;
public class Class86 : Form {
    private Class128 kDiQ;
    private readonly uint kDiF = (uint)Class13.KD3N;
    private readonly ResourceManager lDiL;
    private Dictionary<int, Class80> nDiJ;
    private Dictionary<int, Class80> rDi7;
    private Dictionary<int, Class80> qDiP;
    private Dictionary<int, Class80> EDii;
    private Dictionary<string, uint> lDim;
    private Dictionary<string, byte[]> ODi0;
    private Dictionary<int, string> VDiI;
    private Dictionary<string, int> TDiR;
    private Dictionary<int, int> eDiC;
    private IDisposable kDiK;
    private TableLayoutPanel JDiU;
    private PictureBox DDiT;
    private PictureBox oDi1;
    private PictureBox rDiW;
    private PictureBox HDiw;
    private PictureBox qDiN;
    private PictureBox sDiY;
    private PictureBox bDiB;
    private PictureBox UDiA;
    private PictureBox eDif;
    private Label jDi6;
    private Label vDix;
    private Label hDi9;
    private Label yDic;
    private Label JDiy;
    private Label XDir;
    private Label MDiq;
    private Label WDik;
    private Label iDiM;
    private PictureBox dDiu;
    private PictureBox pDig;
    private PictureBox eDi2;
    private PictureBox aDi3;
    private PictureBox ODid;
    private PictureBox PDiH;
    private Button EDi4;
    private PictureBox cDi5;
    private TableLayoutPanel WDis;
    private PictureBox xDiZ;
    private PictureBox ODia;
    private PictureBox MDij;
    private PictureBox YDiz;
    private PictureBox aDmE;
    private PictureBox sDmD;
    private PictureBox XDmX;
    private PictureBox MDmp;
    private PictureBox hDmS;
    private PictureBox MDmh;
    private Label GDml;
    private Label JDmG;
    private Label EDmb;
    private Label IDmv;
    private Label NDmo;
    private Label qDmt;
    private Label oDmV;
    private Label xDmO;
    private Label PDme;
    private PictureBox bDm8;
    private PictureBox oDmn;
    private PictureBox EDmQ;
    private PictureBox SDmF;
    private PictureBox uDmL;
    private PictureBox FDmJ;
    public Class86(Class128 mbz_0) {
        lDin();
        kDiQ = mbz_0;
    }

    private void gDit(Control control_0, byte[] byte_0) {
        try {
            byte[] array = new byte[Class13.CD3Y];
            int num = 0;
            for (num = 1; byte_0[num] != 0; num++) {
            }

            Array.Copy(byte_0, 0, array, 0, num);
            byte[] bytes = Encoding.GetEncoding(Class13.kD3B).GetBytes(Encoding.Default.GetString(array));
            string text = Encoding.GetEncoding(Class13.BD3A).GetString(bytes).Replace(Class13.HD3f, Class13.sD36);
            control_0.Text = text;
        } catch (Exception) {
            MessageBox.Show(Class13.qD3x);
        }
    }

    private void RDiV() {
        nDiJ = new Dictionary<int, Class80>();
        nDiJ.Add(Class13.xD39, new Class80(lDiL.GetString(Class13.ID3c), Class61.smethod_130(), (uint)Class13.fD3y));
        nDiJ.Add(Class13.mD3r, new Class80(lDiL.GetString(Class13.DD3q), Class61.smethod_131(), (uint)Class13.iD3k));
        nDiJ.Add(Class13.OD3M, new Class80(lDiL.GetString(Class13.eD3u), Class61.smethod_132(), (uint)Class13.oD3g));
        nDiJ.Add(Class13.hD32, new Class80(lDiL.GetString(Class13.QD33), Class61.Gc(), (uint)Class13.XD3d));
        nDiJ.Add(Class13.ED3H, new Class80(lDiL.GetString(Class13.FD34), Class61.Hc(), (uint)Class13.JD35));
        nDiJ.Add(Class13.jD3s, new Class80(lDiL.GetString(Class13.YD3Z), Class61.Tc(), (uint)Class13.MD3a));
        nDiJ.Add(Class13.rD3j, new Class80(lDiL.GetString(Class13.UD3z), Class61.Uc(), (uint)Class13.wDdE));
        nDiJ.Add(Class13.ADdD, new Class80(lDiL.GetString(Class13.EDdX), Class61.pc(), (uint)Class13.pDdp));
        nDiJ.Add(Class13.gDdS, new Class80(lDiL.GetString(Class13.rDdh), Class61.qc(), (uint)Class13.CDdl));
        nDiJ.Add(Class13.GDdG, new Class80(lDiL.GetString(Class13.SDdb), Class61.rc(), (uint)Class13.KDdv));
        nDiJ.Add(Class13.SDdo, new Class80(lDiL.GetString(Class13.ADdt), Class61.Oc(), (uint)Class13.ADdV));
        nDiJ.Add(Class13.BDdO, new Class80(lDiL.GetString(Class13.qDde), Class61.Pc(), (uint)Class13.QDd8));
        nDiJ.Add(Class13.vDdn, new Class80(lDiL.GetString(Class13.iDdQ), Class61.Qc(), (uint)Class13.pDdF));
        nDiJ.Add(Class13.VDdL, new Class80(lDiL.GetString(Class13.kDdJ), Class61.Rc(), (uint)Class13.jDd7));
        nDiJ.Add(Class13.VDdP, new Class80(lDiL.GetString(Class13.hDdi), Class61.Sc(), (uint)Class13.yDdm));
        nDiJ.Add(Class13.dDd0, new Class80(lDiL.GetString(Class13.PDdI), Class61.Ic(), (uint)Class13.lDdR));
        nDiJ.Add(Class13.wDdC, new Class80(lDiL.GetString(Class13.SDdK), Class61.Jc(), (uint)Class13.oDdU));
        nDiJ.Add(Class13.LDdT, new Class80(lDiL.GetString(Class13.HDd1), Class61.Xc(), (uint)Class13.kDdW));
        nDiJ.Add(Class13.cDdw, new Class80(lDiL.GetString(Class13.MDdN), Class61.Yc(), (uint)Class13.bDdY));
        nDiJ.Add(Class13.DDdB, new Class80(lDiL.GetString(Class13.DDdA), Class61.Zc(), (uint)Class13.ODdf));
        nDiJ.Add(Class13.vDd6, new Class80(lDiL.GetString(Class13.sDdx), Class61.sc(), (uint)Class13.YDd9));
        nDiJ.Add(Class13.lDdc, new Class80(lDiL.GetString(Class13.kDdy), Class61.tc(), (uint)Class13.VDdr));
        nDiJ.Add(Class13.RDdq, new Class80(lDiL.GetString(Class13.IDdk), Class61.uc(), (uint)Class13.KDdM));
        nDiJ.Add(Class13.MDdu, new Class80(lDiL.GetString(Class13.WDdg), Class61.Kc(), (uint)Class13.HDd2));
        nDiJ.Add(Class13.FDd3, new Class80(lDiL.GetString(Class13.vDdd), Class61.Lc(), (uint)Class13.tDdH));
        nDiJ.Add(Class13.cDd4, new Class80(lDiL.GetString(Class13.dDd5), Class61.Vc(), (uint)Class13.VDds));
        nDiJ.Add(Class13.TDdZ, new Class80(lDiL.GetString(Class13.DDda), Class61.Wc(), (uint)Class13.xDdj));
        nDiJ.Add(Class13.MDdz, new Class80(lDiL.GetString(Class13.nDHE), Class61.Mc(), (uint)Class13.GDHD));
        nDiJ.Add(Class13.gDHX, new Class80(lDiL.GetString(Class13.bDHp), Class61.Nc(), (uint)Class13.WDHS));
        nDiJ.Add(Class13.KDHh, new Class80(lDiL.GetString(Class13.VDHl), Class61.Ec(), (uint)Class13.jDHG));
        nDiJ.Add(Class13.EDHb, new Class80(lDiL.GetString(Class13.RDHv), Class61.Fc(), (uint)Class13.LDHo));
        nDiJ.Add(Class13.yDHt, new Class80(lDiL.GetString(Class13.yDHV), Class61.Cc(), (uint)Class13.HDHO));
        nDiJ.Add(Class13.wDHe, new Class80(lDiL.GetString(Class13.uDH8), Class61.Dc(), (uint)Class13.pDHn));
        nDiJ.Add(Class13.FDHQ, new Class80(lDiL.GetString(Class13.hDHF), Class61.zc(), (uint)Class13.NDHL));
        nDiJ.Add(Class13.gDHJ, new Class80(lDiL.GetString(Class13.ODH7), Class61.Ac(), (uint)Class13.WDHP));
        nDiJ.Add(Class13.IDHi, new Class80(lDiL.GetString(Class13.SDHm), Class61.Bc(), (uint)Class13.VDH0));
        nDiJ.Add(Class13.DDHI, new Class80(lDiL.GetString(Class13.yDHR), Class61.vc(), (uint)Class13.NDHC));
        nDiJ.Add(Class13.GDHK, new Class80(lDiL.GetString(Class13.UDHU), Class61.wc(), (uint)Class13.jDHT));
        nDiJ.Add(Class13.EDH1, new Class80(lDiL.GetString(Class13.hDHW), Class61.xc(), (uint)Class13.gDHw));
        nDiJ.Add(Class13.LDHN, new Class80(lDiL.GetString(Class13.mDHY), Class61.yc(), (uint)Class13.HDHB));
        nDiJ.Add(Class13.JDHA, new Class80(lDiL.GetString(Class13.HDHf), Class61.smethod_136(), (uint)Class13.VDH6));
        nDiJ.Add(Class13.TDHx, new Class80(lDiL.GetString(Class13.fDH9), Class61.smethod_137(), (uint)Class13.FDHc));
        nDiJ.Add(Class13.FDHy, new Class80(lDiL.GetString(Class13.DDHr), Class61.smethod_133(), (uint)Class13.nDHq));
        nDiJ.Add(Class13.aDHk, new Class80(lDiL.GetString(Class13.KDHM), Class61.smethod_134(), (uint)Class13.VDHu));
        nDiJ.Add(Class13.PDHg, new Class80(lDiL.GetString(Class13.mDH2), Class61.smethod_135(), (uint)Class13.yDH3));
        nDiJ.Add(Class13.nDHd, new Class80(lDiL.GetString(Class13.nDHH), Class61.gc(), (uint)Class13.uDH4));
        nDiJ.Add(Class13.fDH5, new Class80(lDiL.GetString(Class13.JDHs), Class61.hc(), (uint)Class13.aDHZ));
        nDiJ.Add(Class13.tDHa, new Class80(lDiL.GetString(Class13.xDHj), Class61.lc(), (uint)Class13.UDHz));
        nDiJ.Add(Class13.ID4E, new Class80(lDiL.GetString(Class13.OD4D), Class61.mc(), (uint)Class13.dD4X));
        nDiJ.Add(Class13.bD4p, new Class80(lDiL.GetString(Class13.xD4S), Class61.nc(), (uint)Class13.GD4h));
        nDiJ.Add(Class13.sD4l, new Class80(lDiL.GetString(Class13.yD4G), Class61.oc(), (uint)Class13.dD4b));
        nDiJ.Add(Class13.MD4v, new Class80(lDiL.GetString(Class13.yD4o), Class61.ic(), (uint)Class13.PD4t));
        nDiJ.Add(Class13.YD4V, new Class80(lDiL.GetString(Class13.eD4O), Class61.jc(), (uint)Class13.MD4e));
        nDiJ.Add(Class13.vD48, new Class80(lDiL.GetString(Class13.YD4n), Class61.kc(), (uint)Class13.eD4Q));
        nDiJ.Add(Class13.RD4F, new Class80(lDiL.GetString(Class13.kD4L), Class61.bc(), (uint)Class13.yD4J));
        nDiJ.Add(Class13.fD47, new Class80(lDiL.GetString(Class13.pD4P), Class61.cc(), (uint)Class13.lD4i));
        nDiJ.Add(Class13.aD4m, new Class80(lDiL.GetString(Class13.nD40), Class61.dc(), (uint)Class13.nD4I));
        nDiJ.Add(Class13.OD4R, new Class80(lDiL.GetString(Class13.yD4C), Class61.ec(), (uint)Class13.FD4K));
        nDiJ.Add(Class13.tD4U, new Class80(lDiL.GetString(Class13.eD4T), Class61.fc(), (uint)Class13.nD41));
        nDiJ.Add(Class13.LD4W, new Class80(lDiL.GetString(Class13.eD4w), Class61.smethod_120(), (uint)Class13.fD4N));
        nDiJ.Add(Class13.wD4Y, new Class80(lDiL.GetString(Class13.ID4B), Class61.smethod_121(), (uint)Class13.aD4A));
        nDiJ.Add(Class13.yD4f, new Class80(lDiL.GetString(Class13.xD46), Class61.smethod_122(), (uint)Class13.VD4x));
        nDiJ.Add(Class13.sD49, new Class80(lDiL.GetString(Class13.FD4c), Class61.Tb(), (uint)Class13.MD4y));
        nDiJ.Add(Class13.ID4r, new Class80(lDiL.GetString(Class13.hD4q), Class61.Ub(), (uint)Class13.VD4k));
        nDiJ.Add(Class13.aD4M, new Class80(lDiL.GetString(Class13.YD4u), Class61.Vb(), (uint)Class13.FD4g));
        nDiJ.Add(Class13.JD42, new Class80(lDiL.GetString(Class13.eD43), Class61.Wb(), (uint)Class13.qD4d));
        nDiJ.Add(Class13.UD4H, new Class80(lDiL.GetString(Class13.DD44), Class61.Xb(), (uint)Class13.sD45));
        nDiJ.Add(Class13.zD4s, new Class80(lDiL.GetString(Class13.QD4Z), Class61.Yb(), (uint)Class13.bD4a));
        nDiJ.Add(Class13.ND4j, new Class80(lDiL.GetString(Class13.eD4z), Class61.Zb(), (uint)Class13.mD5E));
        nDiJ.Add(Class13.tD5D, new Class80(lDiL.GetString(Class13.ND5X), Class61.Pb(), (uint)Class13.AD5p));
        nDiJ.Add(Class13.rD5S, new Class80(lDiL.GetString(Class13.tD5h), Class61.Qb(), (uint)Class13.VD5l));
        nDiJ.Add(Class13.tD5G, new Class80(lDiL.GetString(Class13.BD5b), Class61.Rb(), (uint)Class13.jD5v));
        nDiJ.Add(Class13.AD5o, new Class80(lDiL.GetString(Class13.WD5t), Class61.Sb(), (uint)Class13.wD5V));
        nDiJ.Add(Class13.rD5O, new Class80(lDiL.GetString(Class13.yD5e), Class61.Mb(), (uint)Class13.tD58));
        nDiJ.Add(Class13.OD5n, new Class80(lDiL.GetString(Class13.aD5Q), Class61.Nb(), (uint)Class13.iD5F));
        nDiJ.Add(Class13.GD5L, new Class80(lDiL.GetString(Class13.WD5J), Class61.Ob(), (uint)Class13.KD57));
        nDiJ.Add(Class13.QD5P, new Class80(lDiL.GetString(Class13.CD5i), Class61.Jb(), (uint)Class13.tD5m));
        nDiJ.Add(Class13.xD50, new Class80(lDiL.GetString(Class13.RD5I), Class61.Kb(), (uint)Class13.WD5R));
        nDiJ.Add(Class13.RD5C, new Class80(lDiL.GetString(Class13.nD5K), Class61.Lb(), (uint)Class13.YD5U));
        nDiJ.Add(Class13.BD5T, new Class80(lDiL.GetString(Class13.nD51), Class61.Fb(), (uint)Class13.mD5W));
        nDiJ.Add(Class13.JD5w, new Class80(lDiL.GetString(Class13.JD5N), Class61.Gb(), (uint)Class13.FD5Y));
        nDiJ.Add(Class13.tD5B, new Class80(lDiL.GetString(Class13.FD5A), Class61.Hb(), (uint)Class13.jD5f));
        nDiJ.Add(Class13.aD56, new Class80(lDiL.GetString(Class13.bD5x), Class61.Ib(), (uint)Class13.TD59));
        nDiJ.Add(Class13.dD5c, new Class80(lDiL.GetString(Class13.LD5y), Class61.smethod_125(), (uint)Class13.rD5r));
        nDiJ.Add(Class13.ND5q, new Class80(lDiL.GetString(Class13.qD5k), Class61.smethod_126(), (uint)Class13.BD5M));
        nDiJ.Add(Class13.kD5u, new Class80(lDiL.GetString(Class13.zD5g), Class61.smethod_127(), (uint)Class13.JD52));
        nDiJ.Add(Class13.hD53, new Class80(lDiL.GetString(Class13.rD5d), Class61.smethod_128(), (uint)Class13.iD5H));
        nDiJ.Add(Class13.ND54, new Class80(lDiL.GetString(Class13.LD55), Class61.smethod_129(), (uint)Class13.lD5s));
        nDiJ.Add(Class13.tD5Z, new Class80(lDiL.GetString(Class13.cD5a), Class61.ac(), (uint)Class13.tD5j));
        nDiJ.Add(Class13.qD5z, new Class80(lDiL.GetString(Class13.wDsE), Class61.smethod_123(), (uint)Class13.vDsD));
        nDiJ.Add(Class13.vDsX, new Class80(lDiL.GetString(Class13.nDsp), Class61.smethod_124(), (uint)Class13.sDsS));
        eDiC = new Dictionary<int, int>();
        eDiC.Add(0, Class13.KDsh);
        eDiC.Add(1, Class13.eDsl);
        eDiC.Add(2, Class13.RDsG);
        eDiC.Add(3, Class13.WDsb);
        eDiC.Add(4, Class13.KDsv);
        eDiC.Add(5, Class13.SDso);
        eDiC.Add(6, Class13.kDst);
        eDiC.Add(7, Class13.VDsV);
        eDiC.Add(8, Class13.sDsO);
        eDiC.Add(Class13.mDse, Class13.sDs8);
        eDiC.Add(Class13.mDsn, Class13.zDsQ);
        eDiC.Add(Class13.YDsF, Class13.aDsL);
        eDiC.Add(Class13.ADsJ, Class13.MDs7);
        eDiC.Add(Class13.ADsP, Class13.UDsi);
        eDiC.Add(Class13.xDsm, Class13.yDs0);
        eDiC.Add(Class13.bDsI, Class13.KDsR);
        eDiC.Add(Class13.IDsC, Class13.qDsK);
        eDiC.Add(Class13.YDsU, Class13.vDsT);
        eDiC.Add(Class13.WDs1, Class13.CDsW);
        eDiC.Add(Class13.bDsw, Class13.RDsN);
        eDiC.Add(Class13.iDsY, Class13.ADsB);
        eDiC.Add(Class13.kDsA, Class13.zDsf);
        eDiC.Add(Class13.nDs6, Class13.ADsx);
        eDiC.Add(Class13.TDs9, Class13.NDsc);
        eDiC.Add(Class13.iDsy, Class13.HDsr);
        eDiC.Add(Class13.zDsq, Class13.EDsk);
        eDiC.Add(Class13.eDsM, Class13.IDsu);
        eDiC.Add(Class13.jDsg, Class13.RDs2);
        eDiC.Add(Class13.nDs3, Class13.UDsd);
        eDiC.Add(Class13.JDsH, Class13.QDs4);
        eDiC.Add(Class13.LDs5, Class13.lDss);
        eDiC.Add(Class13.HDsZ, Class13.aDsa);
        eDiC.Add(Class13.lDsj, Class13.IDsz);
        eDiC.Add(Class13.XDZE, Class13.gDZD);
        eDiC.Add(Class13.RDZX, Class13.vDZp);
        eDiC.Add(Class13.DDZS, Class13.XDZh);
        eDiC.Add(Class13.xDZl, Class13.dDZG);
        eDiC.Add(Class13.bDZb, Class13.CDZv);
        eDiC.Add(Class13.gDZo, Class13.TDZt);
        eDiC.Add(Class13.XDZV, Class13.zDZO);
        eDiC.Add(Class13.KDZe, Class13.kDZ8);
        eDiC.Add(Class13.nDZn, Class13.yDZQ);
        eDiC.Add(Class13.XDZF, Class13.YDZL);
        eDiC.Add(Class13.YDZJ, Class13.kDZ7);
        eDiC.Add(Class13.YDZP, Class13.TDZi);
        eDiC.Add(Class13.XDZm, Class13.RDZ0);
        eDiC.Add(Class13.rDZI, Class13.gDZR);
        eDiC.Add(Class13.FDZC, Class13.bDZK);
        eDiC.Add(Class13.tDZU, Class13.DDZT);
        eDiC.Add(Class13.NDZ1, Class13.EDZW);
        eDiC.Add(Class13.IDZw, Class13.eDZN);
        eDiC.Add(Class13.sDZY, Class13.JDZB);
        eDiC.Add(Class13.yDZA, Class13.DDZf);
        eDiC.Add(Class13.uDZ6, Class13.DDZx);
        eDiC.Add(Class13.kDZ9, Class13.bDZc);
        eDiC.Add(Class13.ADZy, Class13.IDZr);
        eDiC.Add(Class13.WDZq, Class13.ODZk);
        eDiC.Add(Class13.lDZM, Class13.gDZu);
        eDiC.Add(Class13.TDZg, Class13.oDZ2);
        eDiC.Add(Class13.QDZ3, Class13.YDZd);
        eDiC.Add(Class13.MDZH, Class13.fDZ4);
        eDiC.Add(Class13.uDZ5, Class13.iDZs);
        eDiC.Add(Class13.CDZZ, Class13.VDZa);
        eDiC.Add(Class13.xDZj, Class13.eDZz);
        eDiC.Add(Class13.oDaE, Class13.pDaD);
        eDiC.Add(Class13.DDaX, Class13.JDap);
        eDiC.Add(Class13.RDaS, Class13.eDah);
        eDiC.Add(Class13.CDal, Class13.GDaG);
        eDiC.Add(Class13.uDab, Class13.pDav);
        eDiC.Add(Class13.GDao, Class13.SDat);
        eDiC.Add(Class13.bDaV, Class13.UDaO);
        eDiC.Add(Class13.dDae, Class13.jDa8);
        eDiC.Add(Class13.eDan, Class13.NDaQ);
        eDiC.Add(Class13.fDaF, Class13.bDaL);
        eDiC.Add(Class13.UDaJ, Class13.FDa7);
        eDiC.Add(Class13.FDaP, Class13.vDai);
        eDiC.Add(Class13.BDam, Class13.ADa0);
        eDiC.Add(Class13.PDaI, Class13.cDaR);
        eDiC.Add(Class13.ODaC, Class13.UDaK);
        eDiC.Add(Class13.TDaU, Class13.YDaT);
        eDiC.Add(Class13.DDa1, Class13.IDaW);
        eDiC.Add(Class13.JDaw, Class13.sDaN);
        eDiC.Add(Class13.ODaY, Class13.WDaB);
        eDiC.Add(Class13.jDaA, Class13.zDaf);
        eDiC.Add(Class13.cDa6, Class13.SDax);
        eDiC.Add(Class13.gDa9, Class13.JDac);
        eDiC.Add(Class13.CDay, Class13.rDar);
        eDiC.Add(Class13.ODaq, Class13.sDak);
        eDiC.Add(Class13.ADaM, Class13.xDau);
        eDiC.Add(Class13.kDag, Class13.KDa2);
        eDiC.Add(Class13.sDa3, Class13.SDad);
        eDiC.Add(Class13.ADaH, Class13.XDa4);
        eDiC.Add(Class13.kDa5, Class13.xDas);
        eDiC.Add(Class13.EDaZ, Class13.wDaa);
        eDiC.Add(Class13.SDaj, Class13.JDaz);
        eDiC.Add(Class13.xDjE, Class13.PDjD);
        eDiC.Add(Class13.tDjX, Class13.fDjp);
        eDiC.Add(Class13.LDjS, Class13.nDjh);
        eDiC.Add(Class13.ADjl, Class13.LDjG);
        eDiC.Add(Class13.zDjb, Class13.dDjv);
        eDiC.Add(Class13.dDjo, Class13.IDjt);
        eDiC.Add(Class13.RDjV, Class13.fDjO);
        eDiC.Add(Class13.oDje, Class13.RDj8);
        eDiC.Add(Class13.iDjn, Class13.JDjQ);
    }

    private void uDiO() {
        rDi7 = new Dictionary<int, Class80>();
        qDiP = new Dictionary<int, Class80>();
        EDii = new Dictionary<int, Class80>();
        rDi7.Add(1, new Class80(lDiL.GetString(Class13.XDjF), Class61.q5(), 1u, new uint[3] { 1u, 0u, 4u }));
        rDi7.Add(Class13.LDjL, new Class80(lDiL.GetString(Class13.WDjJ), Class61.Y4(), (uint)Class13.iDj7, new uint[3] { 1u, 7u, 12u }));
        rDi7.Add(Class13.GDjP, new Class80(lDiL.GetString(Class13.rDji), Class61.Z4(), (uint)Class13.lDjm, new uint[3] { 1u, 9u, 6u }));
        rDi7.Add(Class13.iDj0, new Class80(lDiL.GetString(Class13.iDjI), Class61.smethod_50(), (uint)Class13.rDjR, new uint[3] { 1u, 11u, 1u }));
        rDi7.Add(Class13.FDjC, new Class80(lDiL.GetString(Class13.TDjK), Class61.smethod_51(), (uint)Class13.zDjU, new uint[3] { 1u, 7u, 3u }));
        rDi7.Add(Class13.FDjT, new Class80(lDiL.GetString(Class13.BDj1), Class61.smethod_52(), (uint)Class13.dDjW, new uint[3] { 3u, 7u, 13u }));
        rDi7.Add(Class13.aDjw, new Class80(lDiL.GetString(Class13.lDjN), Class61.smethod_53(), (uint)Class13.cDjY, new uint[3] { 2u, 7u, 7u }));
        rDi7.Add(Class13.JDjB, new Class80(lDiL.GetString(Class13.KDjA), Class61.smethod_54(), (uint)Class13.GDjf, new uint[3] { 2u, 6u, 6u }));
        rDi7.Add(Class13.yDj6, new Class80(lDiL.GetString(Class13.cDjx), Class61.smethod_55(), (uint)Class13.fDj9, new uint[3] { 2u, 4u, 23u }));
        rDi7.Add(Class13.zDjc, new Class80(lDiL.GetString(Class13.gDjy), Class61.smethod_56(), (uint)Class13.TDjr, new uint[3] { 1u, 4u, 11u }));
        rDi7.Add(Class13.IDjq, new Class80(lDiL.GetString(Class13.MDjk), Class61.smethod_57(), (uint)Class13.lDjM, new uint[3] { 1u, 4u, 9u }));
        rDi7.Add(Class13.UDju, new Class80(lDiL.GetString(Class13.gDjg), Class61.smethod_58(), (uint)Class13.QDj2, new uint[3] { 1u, 2u, 10u }));
        rDi7.Add(Class13.SDj3, new Class80(lDiL.GetString(Class13.FDjd), Class61.smethod_59(), (uint)Class13.HDjH, new uint[3] { 1u, 6u, 10u }));
        rDi7.Add(Class13.qDj4, new Class80(lDiL.GetString(Class13.kDj5), Class61.a5(), (uint)Class13.IDjs, new uint[3] { 1u, 1u, 12u }));
        rDi7.Add(Class13.oDjZ, new Class80(lDiL.GetString(Class13.BDja), Class61.b5(), (uint)Class13.DDjj, new uint[3] { 2u, 13u, 13u }));
        rDi7.Add(Class13.IDjz, new Class80(lDiL.GetString(Class13.TDzE), Class61.c5(), (uint)Class13.ODzD, new uint[3] { 2u, 10u, 1u }));
        rDi7.Add(Class13.JDzX, new Class80(lDiL.GetString(Class13.rDzp), Class61.d5(), (uint)Class13.JDzS, new uint[3] { 3u, (uint)Class13.bDzh, 0u }));
        rDi7.Add(Class13.iDzl, new Class80(lDiL.GetString(Class13.ODzG), Class61.T5(), (uint)Class13.qDzb, new uint[3] { 2u, 8u, 11u }));
        rDi7.Add(Class13.vDzv, new Class80(lDiL.GetString(Class13.YDzo), Class61.U5(), (uint)Class13.hDzt, new uint[3] { 1u, 9u, 2u }));
        rDi7.Add(Class13.iDzV, new Class80(lDiL.GetString(Class13.vDzO), Class61.V5(), (uint)Class13.XDze, new uint[3] { 2u, 8u, 13u }));
        rDi7.Add(Class13.nDz8, new Class80(lDiL.GetString(Class13.yDzn), Class61.W5(), (uint)Class13.uDzQ, new uint[3] { 1u, 7u, 14u }));
        rDi7.Add(Class13.XDzF, new Class80(lDiL.GetString(Class13.KDzL), Class61.X5(), (uint)Class13.jDzJ, new uint[3] { 3u, 5u, 13u }));
        rDi7.Add(Class13.IDz7, new Class80(lDiL.GetString(Class13.DDzP), Class61.Y5(), (uint)Class13.VDzi, new uint[3] { 3u, 7u, 23u }));
        rDi7.Add(Class13.BDzm, new Class80(lDiL.GetString(Class13.lDz0), Class61.f5(), (uint)Class13.jDzI, new uint[3] { 1u, 8u, 9u }));
        rDi7.Add(Class13.tDzR, new Class80(lDiL.GetString(Class13.wDzC), Class61.g5(), (uint)Class13.fDzK, new uint[3] { 2u, 5u, 1u }));
        rDi7.Add(Class13.TDzU, new Class80(lDiL.GetString(Class13.cDzT), Class61.h5(), (uint)Class13.TDz1, new uint[3] { 3u, 5u, 12u }));
        rDi7.Add(Class13.UDzW, new Class80(lDiL.GetString(Class13.gDzw), Class61.i5(), (uint)Class13.fDzN, new uint[3] { 1u, 4u, 15u }));
        rDi7.Add(Class13.sDzY, new Class80(lDiL.GetString(Class13.yDzB), Class61.j5(), (uint)Class13.eDzA, new uint[3] { 2u, 4u, 14u }));
        rDi7.Add(Class13.yDzf, new Class80(lDiL.GetString(Class13.MDz6), Class61.k5(), (uint)Class13.aDzx, new uint[3] { 2u, 5u, 0u }));
        rDi7.Add(Class13.yDz9, new Class80(lDiL.GetString(Class13.NDzc), Class61.l5(), (uint)Class13.lDzy, new uint[3] { 3u, 4u, 8u }));
        rDi7.Add(Class13.QDzr, new Class80(lDiL.GetString(Class13.CDzq), Class61.m5(), (uint)Class13.HDzk, new uint[3] { 2u, 10u, 7u }));
        rDi7.Add(Class13.eDzM, new Class80(lDiL.GetString(Class13.SDzu), Class61.n5(), (uint)Class13.JDzg, new uint[3] { 3u, 3u, 15u }));
        rDi7.Add(Class13.vDz2, new Class80(lDiL.GetString(Class13.hDz3), Class61.o5(), (uint)Class13.hDzd, new uint[3] { 1u, 2u, 11u }));
        rDi7.Add(Class13.nDzH, new Class80(lDiL.GetString(Class13.BDz4), Class61.p5(), (uint)Class13.YDz5, new uint[3] { 3u, 6u, 15u }));
        rDi7.Add(Class13.UDzs, new Class80(lDiL.GetString(Class13.FDzZ), Class61.r5(), (uint)Class13.FDza, new uint[3] { 2u, 5u, 15u }));
        rDi7.Add(Class13.EDzj, new Class80(lDiL.GetString(Class13.SDzz), Class61.s5(), (uint)Class13.jXEE, new uint[3] { 3u, 6u, 2u }));
        rDi7.Add(Class13.FXED, new Class80(lDiL.GetString(Class13.SXEX), Class61.t5(), (uint)Class13.NXEp, new uint[3] { 1u, 9u, 8u }));
        rDi7.Add(Class13.oXES, new Class80(lDiL.GetString(Class13.bXEh), Class61.u5(), (uint)Class13.nXEl, new uint[3] { 1u, 6u, 4u }));
        rDi7.Add(Class13.NXEG, new Class80(lDiL.GetString(Class13.dXEb), Class61.v5(), (uint)Class13.IXEv, new uint[3] { 2u, 9u, 2u }));
        rDi7.Add(Class13.IXEo, new Class80(lDiL.GetString(Class13.YXEt), Class61.w5(), (uint)Class13.vXEV, new uint[3] { 1u, 7u, 11u }));
        rDi7.Add(Class13.NXEO, new Class80(lDiL.GetString(Class13.pXEe), Class61.x5(), (uint)Class13.SXE8, new uint[3] { 2u, 7u, 8u }));
        rDi7.Add(Class13.dXEn, new Class80(lDiL.GetString(Class13.fXEQ), Class61.y5(), (uint)Class13.BXEF, new uint[3] { 2u, 5u, 4u }));
        rDi7.Add(Class13.jXEL, new Class80(lDiL.GetString(Class13.VXEJ), Class61.F5(), (uint)Class13.vXE7, new uint[3] { 2u, 5u, 2u }));
        rDi7.Add(Class13.jXEP, new Class80(lDiL.GetString(Class13.dXEi), Class61.G5(), (uint)Class13.cXEm, new uint[3] { 2u, 5u, 3u }));
        rDi7.Add(Class13.iXE0, new Class80(lDiL.GetString(Class13.LXEI), Class61.H5(), (uint)Class13.WXER, new uint[3] { 2u, 5u, 9u }));
        rDi7.Add(Class13.OXEC, new Class80(lDiL.GetString(Class13.VXEK), Class61.smethod_62(), (uint)Class13.PXEU, new uint[3] { 1u, 1u, 5u }));
        rDi7.Add(Class13.eXET, new Class80(lDiL.GetString(Class13.YXE1), Class61.smethod_63(), (uint)Class13.IXEW, new uint[3] { 1u, 6u, 7u }));
        rDi7.Add(Class13.JXEw, new Class80(lDiL.GetString(Class13.rXEN), Class61.smethod_64(), (uint)Class13.WXEY, new uint[3] { 2u, 10u, 12u }));
        rDi7.Add(Class13.SXEB, new Class80(lDiL.GetString(Class13.XXEA), Class61.I5(), (uint)Class13.NXEf, new uint[3] { 3u, 7u, 4u }));
        rDi7.Add(Class13.AXE6, new Class80(lDiL.GetString(Class13.fXEx), Class61.J5(), (uint)Class13.iXE9, new uint[3] { 3u, 5u, 6u }));
        rDi7.Add(Class13.CXEc, new Class80(lDiL.GetString(Class13.xXEy), Class61.K5(), (uint)Class13.yXEr, new uint[3] { 3u, 5u, 5u }));
        rDi7.Add(Class13.JXEq, new Class80(lDiL.GetString(Class13.XXEk), Class61.L5(), (uint)Class13.mXEM, new uint[3] { 2u, 7u, 10u }));
        rDi7.Add(Class13.rXEu, new Class80(lDiL.GetString(Class13.UXEg), Class61.M5(), (uint)Class13.fXE2, new uint[3] { 3u, 7u, 15u }));
        rDi7.Add(Class13.DXE3, new Class80(lDiL.GetString(Class13.aXEd), Class61.N5(), (uint)Class13.iXEH, new uint[3] { 3u, 5u, 14u }));
        rDi7.Add(Class13.aXE4, new Class80(lDiL.GetString(Class13.HXE5), Class61.O5(), (uint)Class13.CXEs, new uint[3] { 3u, 5u, 23u }));
        rDi7.Add(Class13.fXEZ, new Class80(lDiL.GetString(Class13.qXEa), Class61.P5(), (uint)Class13.tXEj, new uint[3] { 1u, 2u, 3u }));
        rDi7.Add(Class13.YXEz, new Class80(lDiL.GetString(Class13.xXDE), Class61.Q5(), (uint)Class13.WXDD, new uint[3] { 2u, 5u, 10u }));
        rDi7.Add(Class13.kXDX, new Class80(lDiL.GetString(Class13.XXDp), Class61.z5(), (uint)Class13.sXDS, new uint[3] { 1u, 1u, 13u }));
        rDi7.Add(Class13.YXDh, new Class80(lDiL.GetString(Class13.bXDl), Class61.A5(), (uint)Class13.wXDG, new uint[3] { 1u, 1u, 0u }));
        rDi7.Add(Class13.GXDb, new Class80(lDiL.GetString(Class13.IXDv), Class61.B5(), (uint)Class13.UXDo, new uint[3] { 1u, 10u, 23u }));
        rDi7.Add(Class13.OXDt, new Class80(lDiL.GetString(Class13.gXDV), Class61.C5(), (uint)Class13.CXDO, new uint[3] { 1u, 4u, 3u }));
        rDi7.Add(Class13.GXDe, new Class80(lDiL.GetString(Class13.hXD8), Class61.D5(), (uint)Class13.XXDn, new uint[3] { 3u, 10u, 14u }));
        rDi7.Add(Class13.tXDQ, new Class80(lDiL.GetString(Class13.EXDF), Class61.E5(), (uint)Class13.NXDL, new uint[3] { 2u, 14u, 23u }));
        rDi7.Add(Class13.aXDJ, new Class80(lDiL.GetString(Class13.EXD7), Class61.V4(), (uint)Class13.wXDP, new uint[3] { 2u, 99u, 6u }));
        rDi7.Add(Class13.zXDi, new Class80(lDiL.GetString(Class13.aXDm), Class61.W4(), (uint)Class13.gXD0, new uint[3] { 2u, (uint)Class13.kXDI, 0u }));
        rDi7.Add(Class13.aXDR, new Class80(lDiL.GetString(Class13.oXDC), Class61.X4(), (uint)Class13.kXDK, new uint[3] { 2u, 99u, 1u }));
        rDi7.Add(Class13.aXDU, new Class80(lDiL.GetString(Class13.SXDT), Class61.R5(), (uint)Class13.XXD1, new uint[3] { 2u, 98u, 5u }));
        rDi7.Add(Class13.cXDW, new Class80(lDiL.GetString(Class13.wXDw), Class61.S5(), (uint)Class13.NXDN, new uint[3] { 3u, 98u, 14u }));
        rDi7.Add(Class13.KXDY, new Class80(lDiL.GetString(Class13.mXDB), Class61.Z5(), (uint)Class13.lXDA, new uint[3] { 2u, 98u, 12u }));
        rDi7.Add(Class13.sXDf, new Class80(lDiL.GetString(Class13.xXD6), Class61.e5(), (uint)Class13.NXDx, new uint[3] { 3u, 4u, 0u }));
        qDiP.Add(1, new Class80(lDiL.GetString(Class13.LXD9), Class61.L(), 1u, new uint[3] { 1u, 0u, (uint)Class13.wXDc }));
        qDiP.Add(Class13.pXDy, new Class80(lDiL.GetString(Class13.gXDr), Class61.X1(), (uint)Class13.mXDq, new uint[3] { 1u, 0u, 3u }));
        qDiP.Add(Class13.VXDk, new Class80(lDiL.GetString(Class13.qXDM), Class61.Y1(), (uint)Class13.bXDu, new uint[3] { 1u, 10u, 5u }));
        qDiP.Add(Class13.QXDg, new Class80(lDiL.GetString(Class13.FXD2), Class61.smethod_20(), (uint)Class13.gXD3, new uint[3] { 1u, 10u, 19u }));
        qDiP.Add(Class13.KXDd, new Class80(lDiL.GetString(Class13.OXDH), Class61.smethod_21(), (uint)Class13.LXD4, new uint[3] { 2u, 3u, 4u }));
        qDiP.Add(Class13.IXD5, new Class80(lDiL.GetString(Class13.XXDs), Class61.smethod_22(), (uint)Class13.VXDZ, new uint[3] { 1u, 3u, 0u }));
        qDiP.Add(Class13.nXDa, new Class80(lDiL.GetString(Class13.gXDj), Class61.smethod_23(), (uint)Class13.AXDz, new uint[3] { 1u, 0u, 8u }));
        qDiP.Add(Class13.yXXE, new Class80(lDiL.GetString(Class13.tXXD), Class61.smethod_24(), (uint)Class13.XXXX, new uint[3] { 1u, 2u, 7u }));
        qDiP.Add(Class13.fXXp, new Class80(lDiL.GetString(Class13.FXXS), Class61.smethod_25(), (uint)Class13.XXXh, new uint[3] { 1u, 2u, 2u }));
        qDiP.Add(Class13.wXXl, new Class80(lDiL.GetString(Class13.JXXG), Class61.smethod_26(), (uint)Class13.EXXb, new uint[3] { 3u, 7u, 10u }));
        qDiP.Add(Class13.jXXv, new Class80(lDiL.GetString(Class13.jXXo), Class61.smethod_27(), (uint)Class13.vXXt, new uint[3] { 1u, 6u, 6u }));
        qDiP.Add(Class13.tXXV, new Class80(lDiL.GetString(Class13.WXXO), Class61.smethod_28(), (uint)Class13.EXXe, new uint[3] { 1u, 7u, 1u }));
        qDiP.Add(Class13.EXX8, new Class80(lDiL.GetString(Class13.JXXn), Class61.smethod_29(), (uint)Class13.jXXQ, new uint[3] { 1u, 7u, 4u }));
        qDiP.Add(Class13.sXXF, new Class80(lDiL.GetString(Class13.YXXL), Class61.a2(), (uint)Class13.nXXJ, new uint[3] { 1u, 11u, 2u }));
        qDiP.Add(Class13.PXX7, new Class80(lDiL.GetString(Class13.WXXP), Class61.b2(), (uint)Class13.gXXi, new uint[3] { 1u, 11u, 11u }));
        qDiP.Add(Class13.HXXm, new Class80(lDiL.GetString(Class13.zXX0), Class61.c2(), (uint)Class13.mXXI, new uint[3] { 1u, 9u, 3u }));
        qDiP.Add(Class13.pXXR, new Class80(lDiL.GetString(Class13.PXXC), Class61.d2(), (uint)Class13.VXXK, new uint[3] { 1u, 9u, 16u }));
        qDiP.Add(Class13.iXXU, new Class80(lDiL.GetString(Class13.PXXT), Class61.e2(), (uint)Class13.sXX1, new uint[3] { 1u, 7u, 6u }));
        qDiP.Add(Class13.bXXW, new Class80(lDiL.GetString(Class13.TXXw), Class61.f2(), (uint)Class13.XXXN, new uint[3] { 1u, 8u, 8u }));
        qDiP.Add(Class13.OXXY, new Class80(lDiL.GetString(Class13.kXXB), Class61.g2(), (uint)Class13.wXXA, new uint[3] { 1u, 8u, 5u }));
        qDiP.Add(Class13.VXXf, new Class80(lDiL.GetString(Class13.iXX6), Class61.h2(), (uint)Class13.gXXx, new uint[3] { 1u, 6u, 17u }));
        qDiP.Add(Class13.fXX9, new Class80(lDiL.GetString(Class13.PXXc), Class61.i2(), (uint)Class13.UXXy, new uint[3] { 1u, 6u, 1u }));
        qDiP.Add(Class13.oXXr, new Class80(lDiL.GetString(Class13.RXXq), Class61.j2(), (uint)Class13.DXXk, new uint[3] { 3u, 0u, (uint)Class13.cXXM }));
        qDiP.Add(Class13.hXXu, new Class80(lDiL.GetString(Class13.DXXg), Class61.k2(), (uint)Class13.BXX2, new uint[3] { 2u, 0u, (uint)Class13.gXX3 }));
        qDiP.Add(Class13.UXXd, new Class80(lDiL.GetString(Class13.uXXH), Class61.l2(), (uint)Class13.RXX4, new uint[3] { 1u, 12u, 6u }));
        qDiP.Add(Class13.EXX5, new Class80(lDiL.GetString(Class13.yXXs), Class61.m2(), (uint)Class13.kXXZ, new uint[3] { 1u, 12u, 10u }));
        qDiP.Add(Class13.OXXa, new Class80(lDiL.GetString(Class13.UXXj), Class61.n2(), (uint)Class13.WXXz, new uint[3] { 1u, 6u, 1u }));
        qDiP.Add(Class13.IXpE, new Class80(lDiL.GetString(Class13.BXpD), Class61.o2(), (uint)Class13.VXpX, new uint[3] { 1u, 7u, 3u }));
        qDiP.Add(Class13.uXpp, new Class80(lDiL.GetString(Class13.nXpS), Class61.p2(), (uint)Class13.OXph, new uint[3] { 3u, 98u, 16u }));
        qDiP.Add(Class13.OXpl, new Class80(lDiL.GetString(Class13.GXpG), Class61.q2(), (uint)Class13.FXpb, new uint[3] { 1u, 6u, 18u }));
        qDiP.Add(Class13.kXpv, new Class80(lDiL.GetString(Class13.SXpo), Class61.K1(), (uint)Class13.bXpt, new uint[3] { 2u, 8u, 9u }));
        qDiP.Add(Class13.vXpV, new Class80(lDiL.GetString(Class13.fXpO), Class61.L1(), (uint)Class13.tXpe, new uint[3] { 2u, 4u, 11u }));
        qDiP.Add(Class13.kXp8, new Class80(lDiL.GetString(Class13.KXpn), Class61.M1(), (uint)Class13.qXpQ, new uint[3] { 1u, 11u, 12u }));
        qDiP.Add(Class13.wXpF, new Class80(lDiL.GetString(Class13.UXpL), Class61.Class120(), (uint)Class13.dXpJ, new uint[3] { 2u, 8u, 0u }));
        qDiP.Add(Class13.sXp7, new Class80(lDiL.GetString(Class13.hXpP), Class61.O1(), (uint)Class13.oXpi, new uint[3] { 1u, 4u, 1u }));
        qDiP.Add(Class13.TXpm, new Class80(lDiL.GetString(Class13.xXp0), Class61.P1(), (uint)Class13.BXpI, new uint[3] { 1u, 8u, 17u }));
        qDiP.Add(Class13.lXpR, new Class80(lDiL.GetString(Class13.gXpC), Class61.Q1(), (uint)Class13.hXpK, new uint[3] { 1u, 3u, 6u }));
        qDiP.Add(Class13.BXpU, new Class80(lDiL.GetString(Class13.sXpT), Class61.R1(), (uint)Class13.TXp1, new uint[3] { 1u, 3u, 11u }));
        qDiP.Add(Class13.mXpW, new Class80(lDiL.GetString(Class13.hXpw), Class61.S1(), (uint)Class13.hXpN, new uint[3] { 1u, 0u, 4u }));
        qDiP.Add(Class13.KXpY, new Class80(lDiL.GetString(Class13.VXpB), Class61.T1(), (uint)Class13.lXpA, new uint[3] { 1u, 9u, 18u }));
        qDiP.Add(Class13.hXpf, new Class80(lDiL.GetString(Class13.xXp6), Class61.U1(), (uint)Class13.CXpx, new uint[3] { 1u, 0u, (uint)Class13.jXp9 }));
        qDiP.Add(Class13.KXpc, new Class80(lDiL.GetString(Class13.oXpy), Class61.V1(), (uint)Class13.kXpr, new uint[3] { 1u, 1u, 8u }));
        qDiP.Add(Class13.OXpq, new Class80(lDiL.GetString(Class13.DXpk), Class61.W1(), (uint)Class13.qXpM, new uint[3] { 1u, 9u, 11u }));
        qDiP.Add(Class13.nXpu, new Class80(lDiL.GetString(Class13.XXpg), Class61.r2(), (uint)Class13.tXp2, new uint[3] { 1u, 0u, (uint)Class13.YXp3 }));
        qDiP.Add(Class13.aXpd, new Class80(lDiL.GetString(Class13.QXpH), Class61.s2(), (uint)Class13.AXp4, new uint[3] { 1u, 0u, (uint)Class13.gXp5 }));
        qDiP.Add(Class13.fXps, new Class80(lDiL.GetString(Class13.cXpZ), Class61.t2(), (uint)Class13.NXpa, new uint[3] { 1u, 0u, 7u }));
        qDiP.Add(Class13.TXpj, new Class80(lDiL.GetString(Class13.pXpz), Class61.u2(), (uint)Class13.IXSE, new uint[3] { 1u, 0u, 2u }));
        qDiP.Add(Class13.lXSD, new Class80(lDiL.GetString(Class13.CXSX), Class61.v2(), (uint)Class13.wXSp, new uint[3] { 1u, 1u, 0u }));
        qDiP.Add(Class13.QXSS, new Class80(lDiL.GetString(Class13.iXSh), Class61.w2(), (uint)Class13.MXSl, new uint[3] { 3u, 0u, 5u }));
        qDiP.Add(Class13.nXSG, new Class80(lDiL.GetString(Class13.DXSb), Class61.x2(), (uint)Class13.mXSv, new uint[3] { 2u, 11u, 3u }));
        qDiP.Add(Class13.EXSo, new Class80(lDiL.GetString(Class13.eXSt), Class61.y2(), (uint)Class13.jXSV, new uint[3] { 1u, (uint)Class13.CXSO, 0u }));
        qDiP.Add(Class13.TXSe, new Class80(lDiL.GetString(Class13.FXS8), Class61.z2(), (uint)Class13.QXSn, new uint[3] { 2u, 11u, 10u }));
        qDiP.Add(Class13.VXSQ, new Class80(lDiL.GetString(Class13.DXSF), Class61.A2(), (uint)Class13.IXSL, new uint[3] { 2u, 5u, 10u }));
        qDiP.Add(Class13.rXSJ, new Class80(lDiL.GetString(Class13.nXS7), Class61.smethod_16(), (uint)Class13.bXSP, new uint[3] { 1u, 8u, 18u }));
        qDiP.Add(Class13.NXSi, new Class80(lDiL.GetString(Class13.BXSm), Class61.smethod_17(), (uint)Class13.zXS0, new uint[3] { 2u, 11u, 5u }));
        qDiP.Add(Class13.TXSI, new Class80(lDiL.GetString(Class13.IXSR), Class61.smethod_18(), (uint)Class13.BXSC, new uint[3] { 1u, 11u, 9u }));
        qDiP.Add(Class13.FXSK, new Class80(lDiL.GetString(Class13.tXSU), Class61.smethod_19(), (uint)Class13.UXST, new uint[3] { 1u, 8u, 19u }));
        qDiP.Add(Class13.OXS1, new Class80(lDiL.GetString(Class13.OXSW), Class61.a1(), (uint)Class13.GXSw, new uint[3] { 1u, 4u, 17u }));
        qDiP.Add(Class13.OXSN, new Class80(lDiL.GetString(Class13.vXSY), Class61.b1(), (uint)Class13.pXSB, new uint[3] { 2u, 1u, 19u }));
        qDiP.Add(Class13.xXSA, new Class80(lDiL.GetString(Class13.FXSf), Class61.c1(), (uint)Class13.mXS6, new uint[3] { 3u, 10u, 1u }));
        qDiP.Add(Class13.NXSx, new Class80(lDiL.GetString(Class13.jXS9), Class61.d1(), (uint)Class13.IXSc, new uint[3] { 2u, 11u, 1u }));
        qDiP.Add(Class13.SXSy, new Class80(lDiL.GetString(Class13.PXSr), Class61.e1(), (uint)Class13.bXSq, new uint[3] { 1u, (uint)Class13.sXSk, 0u }));
        qDiP.Add(Class13.MXSM, new Class80(lDiL.GetString(Class13.bXSu), Class61.N(), (uint)Class13.xXSg, new uint[3] { 3u, 9u, 17u }));
        qDiP.Add(Class13.XXS2, new Class80(lDiL.GetString(Class13.WXS3), Class61.P(), (uint)Class13.DXSd, new uint[3] { 2u, 9u, 8u }));
        qDiP.Add(Class13.HXSH, new Class80(lDiL.GetString(Class13.OXS4), Class61.Q(), (uint)Class13.JXS5, new uint[3] { 3u, 4u, 0u }));
        qDiP.Add(Class13.LXSs, new Class80(lDiL.GetString(Class13.EXSZ), Class61.R(), (uint)Class13.zXSa, new uint[3] { 2u, 1u, 18u }));
        qDiP.Add(Class13.vXSj, new Class80(lDiL.GetString(Class13.nXSz), Class61.S(), (uint)Class13.BXhE, new uint[3] { 2u, 8u, 17u }));
        qDiP.Add(Class13.GXhD, new Class80(lDiL.GetString(Class13.MXhX), Class61.T(), (uint)Class13.EXhp, new uint[3] { 3u, 3u, 12u }));
        qDiP.Add(Class13.xXhS, new Class80(lDiL.GetString(Class13.PXhh), Class61.Class1(), (uint)Class13.PXhl, new uint[3] { 3u, 3u, 8u }));
        qDiP.Add(Class13.JXhG, new Class80(lDiL.GetString(Class13.qXhb), Class61.V(), (uint)Class13.pXhv, new uint[3] { 3u, 1u, 9u }));
        qDiP.Add(Class13.dXho, new Class80(lDiL.GetString(Class13.eXht), Class61.Class2(), (uint)Class13.xXhV, new uint[3] { 1u, 8u, 7u }));
        qDiP.Add(Class13.tXhO, new Class80(lDiL.GetString(Class13.rXhe), Class61.X(), (uint)Class13.CXh8, new uint[3] { 2u, 5u, 5u }));
        qDiP.Add(Class13.WXhn, new Class80(lDiL.GetString(Class13.pXhQ), Class61.Y(), (uint)Class13.nXhF, new uint[3] { 2u, 5u, 16u }));
        qDiP.Add(Class13.aXhL, new Class80(lDiL.GetString(Class13.XXhJ), Class61.Z(), (uint)Class13.AXh7, new uint[3] { 3u, 5u, 12u }));
        qDiP.Add(Class13.fXhP, new Class80(lDiL.GetString(Class13.MXhi), Class61.smethod_10(), (uint)Class13.oXhm, new uint[3] { 2u, 5u, 2u }));
        qDiP.Add(Class13.BXh0, new Class80(lDiL.GetString(Class13.VXhI), Class61.smethod_11(), (uint)Class13.JXhR, new uint[3] { 3u, 4u, 9u }));
        qDiP.Add(Class13.RXhC, new Class80(lDiL.GetString(Class13.KXhK), Class61.smethod_12(), (uint)Class13.bXhU, new uint[3] { 2u, 4u, 7u }));
        qDiP.Add(Class13.dXhT, new Class80(lDiL.GetString(Class13.gXh1), Class61.smethod_13(), (uint)Class13.DXhW, new uint[3] { 1u, 2u, 5u }));
        qDiP.Add(Class13.YXhw, new Class80(lDiL.GetString(Class13.YXhN), Class61.B2(), (uint)Class13.eXhY, new uint[3] { 2u, 1u, 10u }));
        qDiP.Add(Class13.NXhB, new Class80(lDiL.GetString(Class13.xXhA), Class61.C2(), (uint)Class13.pXhf, new uint[3] { 1u, 1u, 3u }));
        qDiP.Add(Class13.YXh6, new Class80(lDiL.GetString(Class13.TXhx), Class61.D2(), (uint)Class13.HXh9, new uint[3] { 2u, (uint)Class13.UXhc, 0u }));
        qDiP.Add(Class13.qXhy, new Class80(lDiL.GetString(Class13.hXhr), Class61.D1(), (uint)Class13.UXhq, new uint[3] { 1u, 8u, 6u }));
        qDiP.Add(Class13.zXhk, new Class80(lDiL.GetString(Class13.gXhM), Class61.E1(), (uint)Class13.bXhu, new uint[3] { 1u, 0u, (uint)Class13.YXhg }));
        qDiP.Add(Class13.RXh2, new Class80(lDiL.GetString(Class13.MXh3), Class61.F1(), (uint)Class13.GXhd, new uint[3] { 3u, 0u, 1u }));
        qDiP.Add(Class13.oXhH, new Class80(lDiL.GetString(Class13.MXh4), Class61.G1(), (uint)Class13.uXh5, new uint[3] { 2u, 6u, 12u }));
        qDiP.Add(Class13.pXhs, new Class80(lDiL.GetString(Class13.tXhZ), Class61.H1(), (uint)Class13.bXha, new uint[3] { 1u, 8u, 0u }));
        qDiP.Add(Class13.jXhj, new Class80(lDiL.GetString(Class13.NXhz), Class61.I1(), (uint)Class13.xXlE, new uint[3] { 1u, 4u, 8u }));
        qDiP.Add(Class13.CXlD, new Class80(lDiL.GetString(Class13.TXlX), Class61.J1(), (uint)Class13.bXlp, new uint[3] { 2u, 0u, (uint)Class13.mXlS }));
        qDiP.Add(Class13.iXlh, new Class80(lDiL.GetString(Class13.jXll), Class61.k1(), (uint)Class13.xXlG, new uint[3] { 1u, 3u, 2u }));
        qDiP.Add(Class13.UXlb, new Class80(lDiL.GetString(Class13.TXlv), Class61.l1(), (uint)Class13.wXlo, new uint[3] { 1u, 2u, 11u }));
        qDiP.Add(Class13.gXlt, new Class80(lDiL.GetString(Class13.VXlV), Class61.m1(), (uint)Class13.NXlO, new uint[3] { 2u, 4u, 12u }));
        qDiP.Add(Class13.aXle, new Class80(lDiL.GetString(Class13.DXl8), Class61.n1(), (uint)Class13.kXln, new uint[3] { 2u, 8u, 4u }));
        qDiP.Add(Class13.XXlQ, new Class80(lDiL.GetString(Class13.UXlF), Class61.o1(), (uint)Class13.cXlL, new uint[3] { 1u, 1u, 5u }));
        qDiP.Add(Class13.WXlJ, new Class80(lDiL.GetString(Class13.QXl7), Class61.p1(), (uint)Class13.kXlP, new uint[3] { 1u, 5u, 4u }));
        qDiP.Add(Class13.pXli, new Class80(lDiL.GetString(Class13.lXlm), Class61.q1(), (uint)Class13.KXl0, new uint[3] { 2u, 4u, 2u }));
        qDiP.Add(Class13.RXlI, new Class80(lDiL.GetString(Class13.RXlR), Class61.r1(), (uint)Class13.BXlC, new uint[3] { 2u, 8u, 1u }));
        qDiP.Add(Class13.GXlK, new Class80(lDiL.GetString(Class13.DXlU), Class61.s1(), (uint)Class13.QXlT, new uint[3] { 3u, 6u, 7u }));
        qDiP.Add(Class13.yXl1, new Class80(lDiL.GetString(Class13.HXlW), Class61.t1(), (uint)Class13.iXlw, new uint[3] { 2u, 4u, 11u }));
        qDiP.Add(Class13.fXlN, new Class80(lDiL.GetString(Class13.wXlY), Class61.u1(), (uint)Class13.PXlB, new uint[3] { 3u, 3u, 16u }));
        qDiP.Add(Class13.IXlA, new Class80(lDiL.GetString(Class13.XXlf), Class61.v1(), (uint)Class13.cXl6, new uint[3] { 1u, 3u, 3u }));
        qDiP.Add(Class13.eXlx, new Class80(lDiL.GetString(Class13.iXl9), Class61.w1(), (uint)Class13.eXlc, new uint[3] { 2u, 4u, 4u }));
        qDiP.Add(Class13.hXly, new Class80(lDiL.GetString(Class13.KXlr), Class61.x1(), (uint)Class13.EXlq, new uint[3] { 2u, 8u, 11u }));
        qDiP.Add(Class13.dXlk, new Class80(lDiL.GetString(Class13.iXlM), Class61.y1(), (uint)Class13.cXlu, new uint[3] { 1u, 8u, 12u }));
        qDiP.Add(Class13.XXlg, new Class80(lDiL.GetString(Class13.TXl2), Class61.z1(), (uint)Class13.fXl3, new uint[3] { 3u, 8u, 10u }));
        qDiP.Add(Class13.KXld, new Class80(lDiL.GetString(Class13.CXlH), Class61.A1(), (uint)Class13.sXl4, new uint[3] { 2u, 14u, 9u }));
        qDiP.Add(Class13.nXl5, new Class80(lDiL.GetString(Class13.PXls), Class61.E2(), (uint)Class13.oXlZ, new uint[3] { 3u, 9u, 6u }));
        qDiP.Add(Class13.LXla, new Class80(lDiL.GetString(Class13.fXlj), Class61.F2(), (uint)Class13.KXlz, new uint[3] { 3u, 9u, 4u }));
        qDiP.Add(Class13.EXGE, new Class80(lDiL.GetString(Class13.qXGD), Class61.G2(), (uint)Class13.lXGX, new uint[3] { 3u, 6u, 19u }));
        qDiP.Add(Class13.MXGp, new Class80(lDiL.GetString(Class13.JXGS), Class61.H2(), (uint)Class13.PXGh, new uint[3] { 2u, 6u, 16u }));
        qDiP.Add(Class13.NXGl, new Class80(lDiL.GetString(Class13.XXGG), Class61.I2(), (uint)Class13.fXGb, new uint[3] { 1u, 2u, 8u }));
        qDiP.Add(Class13.YXGv, new Class80(lDiL.GetString(Class13.IXGo), Class61.J2(), (uint)Class13.CXGt, new uint[3] { 1u, 2u, 19u }));
        qDiP.Add(Class13.xXGV, new Class80(lDiL.GetString(Class13.RXGO), Class61.f1(), (uint)Class13.DXGe, new uint[3] { 3u, 6u, 9u }));
        qDiP.Add(Class13.oXG8, new Class80(lDiL.GetString(Class13.GXGn), Class61.g1(), (uint)Class13.CXGQ, new uint[3] { 2u, 6u, 8u }));
        qDiP.Add(Class13.zXGF, new Class80(lDiL.GetString(Class13.HXGL), Class61.h1(), (uint)Class13.AXGJ, new uint[3] { 2u, 4u, 18u }));
        qDiP.Add(Class13.KXG7, new Class80(lDiL.GetString(Class13.oXGP), Class61.I(), (uint)Class13.OXGi, new uint[3] { 2u, 99u, 4u }));
        qDiP.Add(Class13.IXGm, new Class80(lDiL.GetString(Class13.TXG0), Class61.J(), (uint)Class13.qXGI, new uint[3] { 2u, 99u, 7u }));
        qDiP.Add(Class13.PXGR, new Class80(lDiL.GetString(Class13.PXGC), Class61.K(), (uint)Class13.mXGK, new uint[3] { 2u, 99u, 9u }));
        qDiP.Add(Class13.sXGU, new Class80(lDiL.GetString(Class13.wXGT), Class61.M(), (uint)Class13.bXG1, new uint[3] { 3u, 0u, (uint)Class13.gXGW }));
        qDiP.Add(Class13.lXGw, new Class80(lDiL.GetString(Class13.UXGN), Class61.smethod_14(), (uint)Class13.gXGY, new uint[3] { 2u, 98u, 6u }));
        qDiP.Add(Class13.YXGB, new Class80(lDiL.GetString(Class13.MXGA), Class61.smethod_15(), (uint)Class13.yXGf, new uint[3] { 3u, 98u, 7u }));
        qDiP.Add(Class13.vXG6, new Class80(lDiL.GetString(Class13.DXGx), Class61.j1(), (uint)Class13.HXG9, new uint[3] { 2u, 98u, 3u }));
        qDiP.Add(Class13.XXGc, new Class80(lDiL.GetString(Class13.GXGy), Class61.i1(), (uint)Class13.mXGr, new uint[3] { 3u, 4u, 19u }));
        EDii.Add(1, new Class80(lDiL.GetString(Class13.aXGq), Class61.smethod_100(), 1u, new uint[3] { 1u, 2u, 10u }));
        EDii.Add(Class13.QXGk, new Class80(lDiL.GetString(Class13.XXGM), Class61.wa(), (uint)Class13.KXGu, new uint[3] { 1u, 4u, 1u }));
        EDii.Add(Class13.vXGg, new Class80(lDiL.GetString(Class13.zXG2), Class61.xa(), (uint)Class13.IXG3, new uint[3] { 1u, 2u, 21u }));
        EDii.Add(Class13.wXGd, new Class80(lDiL.GetString(Class13.JXGH), Class61.ya(), (uint)Class13.iXG4, new uint[3] { 3u, 4u, 3u }));
        EDii.Add(Class13.IXG5, new Class80(lDiL.GetString(Class13.YXGs), Class61.za(), (uint)Class13.UXGZ, new uint[3] { 1u, 1u, 4u }));
        EDii.Add(Class13.CXGa, new Class80(lDiL.GetString(Class13.nXGj), Class61.Aa(), (uint)Class13.rXGz, new uint[3] { 1u, 4u, 6u }));
        EDii.Add(Class13.iXbE, new Class80(lDiL.GetString(Class13.DXbD), Class61.Ba(), (uint)Class13.VXbX, new uint[3] { 2u, 1u, 6u }));
        EDii.Add(Class13.nXbp, new Class80(lDiL.GetString(Class13.qXbS), Class61.Ca(), (uint)Class13.kXbh, new uint[3] { 1u, 2u, 7u }));
        EDii.Add(Class13.wXbl, new Class80(lDiL.GetString(Class13.YXbG), Class61.Da(), (uint)Class13.kXbb, new uint[3] { 2u, 1u, 21u }));
        EDii.Add(Class13.TXbv, new Class80(lDiL.GetString(Class13.HXbo), Class61.Ea(), (uint)Class13.kXbt, new uint[3] { 3u, 8u, 3u }));
        EDii.Add(Class13.AXbV, new Class80(lDiL.GetString(Class13.XXbO), Class61.Fa(), (uint)Class13.NXbe, new uint[3] { 1u, 8u, 22u }));
        EDii.Add(Class13.bXb8, new Class80(lDiL.GetString(Class13.yXbn), Class61.Ga(), (uint)Class13.LXbQ, new uint[3] { 3u, 11u, 21u }));
        EDii.Add(Class13.TXbF, new Class80(lDiL.GetString(Class13.LXbL), Class61.Ha(), (uint)Class13.MXbJ, new uint[3] { 2u, 11u, 22u }));
        EDii.Add(Class13.FXb7, new Class80(lDiL.GetString(Class13.VXbP), Class61.ca(), (uint)Class13.VXbi, new uint[3] { 1u, 1u, 2u }));
        EDii.Add(Class13.VXbm, new Class80(lDiL.GetString(Class13.aXb0), Class61.da(), (uint)Class13.dXbI, new uint[3] { 1u, 1u, 7u }));
        EDii.Add(Class13.TXbR, new Class80(lDiL.GetString(Class13.mXbC), Class61.ea(), (uint)Class13.DXbK, new uint[3] { 1u, 2u, 20u }));
        EDii.Add(Class13.HXbU, new Class80(lDiL.GetString(Class13.BXbT), Class61.fa(), (uint)Class13.NXb1, new uint[3] { 1u, 1u, 8u }));
        EDii.Add(Class13.sXbW, new Class80(lDiL.GetString(Class13.uXbw), Class61.ga(), (uint)Class13.XXbN, new uint[3] { 1u, 2u, 4u }));
        EDii.Add(Class13.PXbY, new Class80(lDiL.GetString(Class13.tXbB), Class61.ha(), (uint)Class13.YXbA, new uint[3] { 2u, 2u, 22u }));
        EDii.Add(Class13.UXbf, new Class80(lDiL.GetString(Class13.vXb6), Class61.ia(), (uint)Class13.aXbx, new uint[3] { 2u, 1u, 5u }));
        EDii.Add(Class13.RXb9, new Class80(lDiL.GetString(Class13.bXbc), Class61.ja(), (uint)Class13.nXby, new uint[3] { 2u, 13u, 6u }));
        EDii.Add(Class13.yXbr, new Class80(lDiL.GetString(Class13.LXbq), Class61.ka(), (uint)Class13.EXbk, new uint[3] { 1u, 8u, 12u }));
        EDii.Add(Class13.hXbM, new Class80(lDiL.GetString(Class13.NXbu), Class61.la(), (uint)Class13.EXbg, new uint[3] { 1u, 8u, 4u }));
        EDii.Add(Class13.QXb2, new Class80(lDiL.GetString(Class13.WXb3), Class61.ma(), (uint)Class13.XXbd, new uint[3] { 1u, 10u, 12u }));
        EDii.Add(Class13.XXbH, new Class80(lDiL.GetString(Class13.dXb4), Class61.na(), (uint)Class13.tXb5, new uint[3] { 1u, 11u, 2u }));
        EDii.Add(Class13.dXbs, new Class80(lDiL.GetString(Class13.VXbZ), Class61.oa(), (uint)Class13.HXba, new uint[3] { 1u, 10u, 22u }));
        EDii.Add(Class13.vXbj, new Class80(lDiL.GetString(Class13.MXbz), Class61.pa(), (uint)Class13.jXvE, new uint[3] { 2u, 11u, 8u }));
        EDii.Add(Class13.JXvD, new Class80(lDiL.GetString(Class13.hXvX), Class61.qa(), (uint)Class13.fXvp, new uint[3] { 1u, (uint)Class13.LXvS, 0u }));
        EDii.Add(Class13.YXvh, new Class80(lDiL.GetString(Class13.MXvl), Class61.ra(), (uint)Class13.LXvG, new uint[3] { 1u, 10u, 7u }));
        EDii.Add(Class13.OXvb, new Class80(lDiL.GetString(Class13.IXvv), Class61.sa(), (uint)Class13.VXvo, new uint[3] { 3u, 10u, 10u }));
        EDii.Add(Class13.RXvt, new Class80(lDiL.GetString(Class13.mXvV), Class61.ta(), (uint)Class13.MXvO, new uint[3] { 1u, 10u, 5u }));
        EDii.Add(Class13.uXve, new Class80(lDiL.GetString(Class13.DXv8), Class61.ua(), (uint)Class13.LXvn, new uint[3] { 3u, 11u, 20u }));
        EDii.Add(Class13.lXvQ, new Class80(lDiL.GetString(Class13.uXvF), Class61.va(), (uint)Class13.iXvL, new uint[3] { 1u, 10u, 9u }));
        EDii.Add(Class13.WXvJ, new Class80(lDiL.GetString(Class13.xXv7), Class61.smethod_109(), (uint)Class13.eXvP, new uint[3] { 1u, 2u, 5u }));
        EDii.Add(Class13.PXvi, new Class80(lDiL.GetString(Class13.eXvm), Class61.aa(), (uint)Class13.NXv0, new uint[3] { 2u, 2u, 9u }));
        EDii.Add(Class13.hXvI, new Class80(lDiL.GetString(Class13.GXvR), Class61.ba(), (uint)Class13.qXvC, new uint[3] { 2u, 14u, 5u }));
        EDii.Add(Class13.WXvK, new Class80(lDiL.GetString(Class13.GXvU), Class61.Y9(), (uint)Class13.nXvT, new uint[3] { 1u, 2u, 3u }));
        EDii.Add(Class13.tXv1, new Class80(lDiL.GetString(Class13.CXvW), Class61.Z9(), (uint)Class13.KXvw, new uint[3] { 2u, 2u, 0u }));
        EDii.Add(Class13.eXvN, new Class80(lDiL.GetString(Class13.EXvY), Class61.Na(), (uint)Class13.AXvB, new uint[3] { 2u, 9u, 4u }));
        EDii.Add(Class13.sXvA, new Class80(lDiL.GetString(Class13.pXvf), Class61.Oa(), (uint)Class13.PXv6, new uint[3] { 2u, 9u, 8u }));
        EDii.Add(Class13.JXvx, new Class80(lDiL.GetString(Class13.JXv9), Class61.Pa(), (uint)Class13.eXvc, new uint[3] { 3u, 9u, 21u }));
        EDii.Add(Class13.pXvy, new Class80(lDiL.GetString(Class13.QXvr), Class61.M9(), (uint)Class13.GXvq, new uint[3] { 2u, 3u, 9u }));
        EDii.Add(Class13.TXvk, new Class80(lDiL.GetString(Class13.PXvM), Class61.N9(), (uint)Class13.DXvu, new uint[3] { 2u, 3u, 12u }));
        EDii.Add(Class13.QXvg, new Class80(lDiL.GetString(Class13.UXv2), Class61.O9(), (uint)Class13.lXv3, new uint[3] { 3u, 3u, 11u }));
        EDii.Add(Class13.lXvd, new Class80(lDiL.GetString(Class13.tXvH), Class61.P9(), (uint)Class13.oXv4, new uint[3] { 3u, 3u, 22u }));
        EDii.Add(Class13.OXv5, new Class80(lDiL.GetString(Class13.XXvs), Class61.Q9(), (uint)Class13.KXvZ, new uint[3] { 2u, 9u, 20u }));
        EDii.Add(Class13.XXva, new Class80(lDiL.GetString(Class13.XXvj), Class61.R9(), (uint)Class13.cXvz, new uint[3] { 1u, 9u, 5u }));
        EDii.Add(Class13.hXoE, new Class80(lDiL.GetString(Class13.CXoD), Class61.S9(), (uint)Class13.gXoX, new uint[3] { 2u, 3u, 7u }));
        EDii.Add(Class13.pXop, new Class80(lDiL.GetString(Class13.PXoS), Class61.T9(), (uint)Class13.yXoh, new uint[3] { 3u, 3u, 21u }));
        EDii.Add(Class13.dXol, new Class80(lDiL.GetString(Class13.jXoG), Class61.U9(), (uint)Class13.mXob, new uint[3] { 2u, 3u, 10u }));
        EDii.Add(Class13.QXov, new Class80(lDiL.GetString(Class13.WXoo), Class61.V9(), (uint)Class13.OXot, new uint[3] { 1u, (uint)Class13.TXoV, 0u }));
        EDii.Add(Class13.FXoO, new Class80(lDiL.GetString(Class13.oXoe), Class61.W9(), (uint)Class13.eXo8, new uint[3] { 3u, 10u, 11u }));
        EDii.Add(Class13.NXon, new Class80(lDiL.GetString(Class13.CXoQ), Class61.X9(), (uint)Class13.vXoF, new uint[3] { 3u, 10u, 20u }));
        EDii.Add(Class13.nXoL, new Class80(lDiL.GetString(Class13.PXoJ), Class61.Ia(), (uint)Class13.uXo7, new uint[3] { 1u, 2u, 12u }));
        EDii.Add(Class13.GXoP, new Class80(lDiL.GetString(Class13.vXoi), Class61.Ja(), (uint)Class13.gXom, new uint[3] { 1u, 2u, 11u }));
        EDii.Add(Class13.TXo0, new Class80(lDiL.GetString(Class13.PXoI), Class61.Ka(), (uint)Class13.aXoR, new uint[3] { 2u, 2u, 1u }));
        EDii.Add(Class13.XXoC, new Class80(lDiL.GetString(Class13.aXoK), Class61.smethod_101(), (uint)Class13.eXoU, new uint[3] { 1u, 3u, 6u }));
        EDii.Add(Class13.dXoT, new Class80(lDiL.GetString(Class13.gXo1), Class61.smethod_102(), (uint)Class13.rXoW, new uint[3] { 2u, 3u, 20u }));
        EDii.Add(Class13.bXow, new Class80(lDiL.GetString(Class13.bXoN), Class61.smethod_103(), (uint)Class13.cXoY, new uint[3] { 2u, 3u, 7u }));
        EDii.Add(Class13.aXoB, new Class80(lDiL.GetString(Class13.bXoA), Class61.smethod_104(), (uint)Class13.aXof, new uint[3] { 1u, 3u, 9u }));
        EDii.Add(Class13.vXo6, new Class80(lDiL.GetString(Class13.JXox), Class61.smethod_105(), (uint)Class13.wXo9, new uint[3] { 1u, 3u, 1u }));
        EDii.Add(Class13.tXoc, new Class80(lDiL.GetString(Class13.BXoy), Class61.J9(), (uint)Class13.NXor, new uint[3] { 2u, 99u, 3u }));
        EDii.Add(Class13.WXoq, new Class80(lDiL.GetString(Class13.cXok), Class61.K9(), (uint)Class13.YXoM, new uint[3] { 2u, 99u, 8u }));
        EDii.Add(Class13.AXou, new Class80(lDiL.GetString(Class13.uXog), Class61.L9(), (uint)Class13.GXo2, new uint[3] { 2u, 99u, 2u }));
        EDii.Add(Class13.QXo3, new Class80(lDiL.GetString(Class13.wXod), Class61.smethod_106(), (uint)Class13.DXoH, new uint[3] { 2u, 98u, 11u }));
        EDii.Add(Class13.WXo4, new Class80(lDiL.GetString(Class13.xXo5), Class61.smethod_107(), (uint)Class13.TXos, new uint[3] { 3u, 98u, 2u }));
        EDii.Add(Class13.kXoZ, new Class80(lDiL.GetString(Class13.cXoa), Class61.smethod_108(), (uint)Class13.pXoj, new uint[3] { 2u, 98u, 10u }));
    }

    private void dDie() {
        try {
            Label[] array = new Label[4]
            {
                XDir,
                MDiq,
                WDik,
                iDiM
            };
            Label[] array2 = new Label[4]
            {
                qDmt,
                oDmV,
                xDmO,
                PDme
            };
            PictureBox[] array3 = new PictureBox[4]
            {
                dDiu,
                pDig,
                eDi2,
                aDi3
            };
            PictureBox[] array4 = new PictureBox[4]
            {
                bDm8,
                oDmn,
                EDmQ,
                SDmF
            };
            PictureBox[] array5 = new PictureBox[4]
            {
                DDiT,
                rDiW,
                PDiH,
                ODid
            };
            PictureBox[] array6 = new PictureBox[4]
            {
                xDiZ,
                YDiz,
                uDmL,
                FDmJ
            };
            PictureBox[] array7 = new PictureBox[4]
            {
                oDi1,
                HDiw,
                sDiY,
                UDiA
            };
            PictureBox[] array8 = new PictureBox[4]
            {
                ODia,
                aDmE,
                XDmX,
                hDmS
            };
            PictureBox[] array9 = new PictureBox[4]
            {
                cDi5,
                qDiN,
                bDiB,
                eDif
            };
            PictureBox[] array10 = new PictureBox[4]
            {
                MDij,
                sDmD,
                MDmp,
                MDmh
            };
            MemoryStream memoryStream = new MemoryStream();
            uint num = kDiQ.pjJd(Class13.QXoz);
            kDiQ.hD7u(num, num + (uint)Class13.HXtE, memoryStream);
            byte[] buffer = memoryStream.GetBuffer();
            int[] array11 = new int[4]
            {
                -1,
                -1,
                -1,
                -1
            };
            int[] array12 = new int[4]
            {
                -1,
                -1,
                -1,
                -1
            };
            int num2 = 0;
            int num3 = 0;
            byte[] array13 = new byte[Class13.XXtD];
            for (int i = 0; i < 8; i++) {
                int num4 = i * Class13.pXtX;
                if (buffer[Class13.zXtS + num4 + 3] == 0) {
                    array11[num2++] = i;
                } else if (buffer[Class13.xXth + num4 + 3] == 1) {
                    array12[num3++] = i;
                }
            }

            for (int j = 0; j < 4; j++) {
                if (array11[j] > -1) {
                    int num5 = array11[j] * Class13.sXtl;
                    Array.Copy(buffer, num5 + Class13.AXtG, array13, 0, Class13.OXtb);
                    gDit(array[j], array13);
                    int key = buffer[num5 + Class13.FXtv] * Class13.KXto + buffer[num5 + Class13.dXtt];
                    int key2 = buffer[num5 + Class13.EXtV] * Class13.pXtO + buffer[num5 + Class13.bXte];
                    int key3 = buffer[num5 + Class13.PXt8] * Class13.DXtn + buffer[num5 + Class13.RXtQ];
                    int key4 = buffer[num5 + Class13.MXtF] * Class13.cXtL + buffer[num5 + Class13.TXtJ];
                    array3[j].Image = nDiJ[eDiC[key]].PDQX;
                    array5[j].Image = rDi7[key2].PDQX;
                    array7[j].Image = qDiP[key3].PDQX;
                    array9[j].Image = EDii[key4].PDQX;
                } else {
                    array[j].Text = Class13.JXt7;
                    array3[j].Image = Class61.cb();
                    array5[j].Image = Class61.cb();
                    array7[j].Image = Class61.cb();
                    array9[j].Image = Class61.cb();
                }

                if (array12[j] > -1) {
                    int num6 = array12[j] * Class13.nXtP;
                    Array.Copy(buffer, num6 + Class13.XXti, array13, 0, Class13.PXtm);
                    gDit(array2[j], array13);
                    int key5 = buffer[num6 + Class13.JXt0] * Class13.VXtI + buffer[num6 + Class13.zXtR];
                    int key6 = buffer[num6 + Class13.FXtC] * Class13.CXtK + buffer[num6 + Class13.MXtU];
                    int key7 = buffer[num6 + Class13.fXtT] * Class13.DXt1 + buffer[num6 + Class13.TXtW];
                    int key8 = buffer[num6 + Class13.dXtw] * Class13.QXtN + buffer[num6 + Class13.iXtY];
                    array4[j].Image = nDiJ[eDiC[key5]].PDQX;
                    array6[j].Image = rDi7[key6].PDQX;
                    array8[j].Image = qDiP[key7].PDQX;
                    array10[j].Image = EDii[key8].PDQX;
                } else {
                    array2[j].Text = Class13.AXtB;
                    array4[j].Image = Class61.cb();
                    array6[j].Image = Class61.cb();
                    array8[j].Image = Class61.cb();
                    array10[j].Image = Class61.cb();
                }
            }
        } catch (Exception) {
            MessageBox.Show(Class13.dXtA);
        }
    }

    private void aDi8(object sender, EventArgs e) {
        dDie();
    }

    protected override void Dispose(bool disposing) {
        if (disposing && kDiK != null) {
            kDiK.Dispose();
        }

        base.Dispose(disposing);
    }

    private void lDin() {
        ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof(Class86));
        JDiU = new TableLayoutPanel();
        DDiT = new PictureBox();
        oDi1 = new PictureBox();
        cDi5 = new PictureBox();
        rDiW = new PictureBox();
        HDiw = new PictureBox();
        qDiN = new PictureBox();
        sDiY = new PictureBox();
        bDiB = new PictureBox();
        UDiA = new PictureBox();
        eDif = new PictureBox();
        jDi6 = new Label();
        vDix = new Label();
        hDi9 = new Label();
        yDic = new Label();
        JDiy = new Label();
        XDir = new Label();
        MDiq = new Label();
        WDik = new Label();
        iDiM = new Label();
        dDiu = new PictureBox();
        pDig = new PictureBox();
        eDi2 = new PictureBox();
        aDi3 = new PictureBox();
        ODid = new PictureBox();
        PDiH = new PictureBox();
        EDi4 = new Button();
        WDis = new TableLayoutPanel();
        xDiZ = new PictureBox();
        ODia = new PictureBox();
        MDij = new PictureBox();
        YDiz = new PictureBox();
        aDmE = new PictureBox();
        sDmD = new PictureBox();
        XDmX = new PictureBox();
        MDmp = new PictureBox();
        hDmS = new PictureBox();
        MDmh = new PictureBox();
        GDml = new Label();
        JDmG = new Label();
        EDmb = new Label();
        IDmv = new Label();
        NDmo = new Label();
        qDmt = new Label();
        oDmV = new Label();
        xDmO = new Label();
        PDme = new Label();
        bDm8 = new PictureBox();
        oDmn = new PictureBox();
        EDmQ = new PictureBox();
        SDmF = new PictureBox();
        uDmL = new PictureBox();
        FDmJ = new PictureBox();
        JDiU.SuspendLayout();
        ((ISupportInitialize)DDiT).BeginInit();
        ((ISupportInitialize)oDi1).BeginInit();
        ((ISupportInitialize)cDi5).BeginInit();
        ((ISupportInitialize)rDiW).BeginInit();
        ((ISupportInitialize)HDiw).BeginInit();
        ((ISupportInitialize)qDiN).BeginInit();
        ((ISupportInitialize)sDiY).BeginInit();
        ((ISupportInitialize)bDiB).BeginInit();
        ((ISupportInitialize)UDiA).BeginInit();
        ((ISupportInitialize)eDif).BeginInit();
        ((ISupportInitialize)dDiu).BeginInit();
        ((ISupportInitialize)pDig).BeginInit();
        ((ISupportInitialize)eDi2).BeginInit();
        ((ISupportInitialize)aDi3).BeginInit();
        ((ISupportInitialize)ODid).BeginInit();
        ((ISupportInitialize)PDiH).BeginInit();
        WDis.SuspendLayout();
        ((ISupportInitialize)xDiZ).BeginInit();
        ((ISupportInitialize)ODia).BeginInit();
        ((ISupportInitialize)MDij).BeginInit();
        ((ISupportInitialize)YDiz).BeginInit();
        ((ISupportInitialize)aDmE).BeginInit();
        ((ISupportInitialize)sDmD).BeginInit();
        ((ISupportInitialize)XDmX).BeginInit();
        ((ISupportInitialize)MDmp).BeginInit();
        ((ISupportInitialize)hDmS).BeginInit();
        ((ISupportInitialize)MDmh).BeginInit();
        ((ISupportInitialize)bDm8).BeginInit();
        ((ISupportInitialize)oDmn).BeginInit();
        ((ISupportInitialize)EDmQ).BeginInit();
        ((ISupportInitialize)SDmF).BeginInit();
        ((ISupportInitialize)uDmL).BeginInit();
        ((ISupportInitialize)FDmJ).BeginInit();
        SuspendLayout();
        JDiU.ColumnCount = 5;
        JDiU.ColumnStyles.Add(new ColumnStyle());
        JDiU.ColumnStyles.Add(new ColumnStyle());
        JDiU.ColumnStyles.Add(new ColumnStyle());
        JDiU.ColumnStyles.Add(new ColumnStyle());
        JDiU.ColumnStyles.Add(new ColumnStyle());
        JDiU.Controls.Add(DDiT, 2, 1);
        JDiU.Controls.Add(oDi1, 3, 1);
        JDiU.Controls.Add(cDi5, 4, 1);
        JDiU.Controls.Add(rDiW, 2, 2);
        JDiU.Controls.Add(HDiw, 3, 2);
        JDiU.Controls.Add(qDiN, 4, 2);
        JDiU.Controls.Add(sDiY, 3, 3);
        JDiU.Controls.Add(bDiB, 4, 3);
        JDiU.Controls.Add(UDiA, 3, 4);
        JDiU.Controls.Add(eDif, 4, 4);
        JDiU.Controls.Add(jDi6, 0, 0);
        JDiU.Controls.Add(vDix, 1, 0);
        JDiU.Controls.Add(hDi9, 2, 0);
        JDiU.Controls.Add(yDic, 3, 0);
        JDiU.Controls.Add(JDiy, 4, 0);
        JDiU.Controls.Add(XDir, 0, 1);
        JDiU.Controls.Add(MDiq, 0, 2);
        JDiU.Controls.Add(WDik, 0, 3);
        JDiU.Controls.Add(iDiM, 0, 4);
        JDiU.Controls.Add(dDiu, 1, 1);
        JDiU.Controls.Add(pDig, 1, 2);
        JDiU.Controls.Add(eDi2, 1, 3);
        JDiU.Controls.Add(aDi3, 1, 4);
        JDiU.Controls.Add(ODid, 2, 3);
        JDiU.Controls.Add(PDiH, 2, 4);
        JDiU.Location = new Point(Class13.VXtf, Class13.qXt6);
        JDiU.Name = Class13.BXtx;
        JDiU.RowCount = 5;
        JDiU.RowStyles.Add(new RowStyle());
        JDiU.RowStyles.Add(new RowStyle());
        JDiU.RowStyles.Add(new RowStyle());
        JDiU.RowStyles.Add(new RowStyle());
        JDiU.RowStyles.Add(new RowStyle());
        JDiU.RowStyles.Add(new RowStyle(SizeType.Absolute, Class13.XXt9));
        JDiU.Size = new Size(Class13.LXtc, Class13.oXty);
        JDiU.TabIndex = Class13.IXtr;
        DDiT.Anchor = AnchorStyles.None;
        DDiT.BackColor = Color.DarkGray;
        DDiT.BackgroundImageLayout = ImageLayout.Center;
        DDiT.Image = (Image)componentResourceManager.GetObject(Class13.nXtq);
        DDiT.Location = new Point(Class13.gXtk, Class13.BXtM);
        DDiT.Name = Class13.yXtu;
        DDiT.Size = new Size(Class13.yXtg, Class13.HXt2);
        DDiT.SizeMode = PictureBoxSizeMode.StretchImage;
        DDiT.TabIndex = 3;
        DDiT.TabStop = false;
        oDi1.Anchor = AnchorStyles.None;
        oDi1.BackColor = Color.DarkGray;
        oDi1.BackgroundImageLayout = ImageLayout.Center;
        oDi1.Image = (Image)componentResourceManager.GetObject(Class13.LXt3);
        oDi1.Location = new Point(Class13.NXtd, Class13.GXtH);
        oDi1.Name = Class13.mXt4;
        oDi1.Size = new Size(Class13.uXt5, Class13.cXts);
        oDi1.SizeMode = PictureBoxSizeMode.StretchImage;
        oDi1.TabIndex = 4;
        oDi1.TabStop = false;
        cDi5.Anchor = AnchorStyles.None;
        cDi5.BackColor = Color.DarkGray;
        cDi5.BackgroundImageLayout = ImageLayout.Center;
        cDi5.Image = (Image)componentResourceManager.GetObject(Class13.UXtZ);
        cDi5.Location = new Point(Class13.XXta, Class13.YXtj);
        cDi5.Name = Class13.VXtz;
        cDi5.Size = new Size(Class13.nXVE, Class13.kXVD);
        cDi5.SizeMode = PictureBoxSizeMode.StretchImage;
        cDi5.TabIndex = 5;
        cDi5.TabStop = false;
        rDiW.Anchor = AnchorStyles.None;
        rDiW.BackColor = Color.DarkGray;
        rDiW.BackgroundImageLayout = ImageLayout.Center;
        rDiW.Image = (Image)componentResourceManager.GetObject(Class13.pXVX);
        rDiW.Location = new Point(Class13.CXVp, Class13.uXVS);
        rDiW.Name = Class13.lXVh;
        rDiW.Size = new Size(Class13.WXVl, Class13.mXVG);
        rDiW.SizeMode = PictureBoxSizeMode.StretchImage;
        rDiW.TabIndex = 6;
        rDiW.TabStop = false;
        HDiw.Anchor = AnchorStyles.None;
        HDiw.BackColor = Color.DarkGray;
        HDiw.BackgroundImageLayout = ImageLayout.Center;
        HDiw.Image = (Image)componentResourceManager.GetObject(Class13.sXVb);
        HDiw.Location = new Point(Class13.WXVv, Class13.BXVo);
        HDiw.Name = Class13.eXVt;
        HDiw.Size = new Size(Class13.jXVV, Class13.cXVO);
        HDiw.SizeMode = PictureBoxSizeMode.StretchImage;
        HDiw.TabIndex = 7;
        HDiw.TabStop = false;
        qDiN.Anchor = AnchorStyles.None;
        qDiN.BackColor = Color.DarkGray;
        qDiN.BackgroundImageLayout = ImageLayout.Center;
        qDiN.Image = (Image)componentResourceManager.GetObject(Class13.vXVe);
        qDiN.Location = new Point(Class13.GXV8, Class13.MXVn);
        qDiN.Name = Class13.fXVQ;
        qDiN.Size = new Size(Class13.AXVF, Class13.oXVL);
        qDiN.SizeMode = PictureBoxSizeMode.StretchImage;
        qDiN.TabIndex = 8;
        qDiN.TabStop = false;
        sDiY.Anchor = AnchorStyles.None;
        sDiY.BackColor = Color.DarkGray;
        sDiY.BackgroundImageLayout = ImageLayout.Center;
        sDiY.Image = (Image)componentResourceManager.GetObject(Class13.iXVJ);
        sDiY.Location = new Point(Class13.GXV7, Class13.HXVP);
        sDiY.Name = Class13.AXVi;
        sDiY.Size = new Size(Class13.IXVm, Class13.wXV0);
        sDiY.SizeMode = PictureBoxSizeMode.StretchImage;
        sDiY.TabIndex = Class13.kXVI;
        sDiY.TabStop = false;
        bDiB.Anchor = AnchorStyles.None;
        bDiB.BackColor = Color.DarkGray;
        bDiB.BackgroundImageLayout = ImageLayout.Center;
        bDiB.Image = (Image)componentResourceManager.GetObject(Class13.cXVR);
        bDiB.Location = new Point(Class13.DXVC, Class13.kXVK);
        bDiB.Name = Class13.AXVU;
        bDiB.Size = new Size(Class13.uXVT, Class13.dXV1);
        bDiB.SizeMode = PictureBoxSizeMode.StretchImage;
        bDiB.TabIndex = Class13.DXVW;
        bDiB.TabStop = false;
        UDiA.Anchor = AnchorStyles.None;
        UDiA.BackColor = Color.DarkGray;
        UDiA.BackgroundImageLayout = ImageLayout.Center;
        UDiA.Image = (Image)componentResourceManager.GetObject(Class13.cXVw);
        UDiA.Location = new Point(Class13.fXVN, Class13.bXVY);
        UDiA.Name = Class13.jXVB;
        UDiA.Size = new Size(Class13.xXVA, Class13.zXVf);
        UDiA.SizeMode = PictureBoxSizeMode.StretchImage;
        UDiA.TabIndex = Class13.BXV6;
        UDiA.TabStop = false;
        eDif.Anchor = AnchorStyles.None;
        eDif.BackColor = Color.DarkGray;
        eDif.BackgroundImageLayout = ImageLayout.Center;
        eDif.Image = (Image)componentResourceManager.GetObject(Class13.kXVx);
        eDif.Location = new Point(Class13.zXV9, Class13.eXVc);
        eDif.Name = Class13.cXVy;
        eDif.Size = new Size(Class13.vXVr, Class13.JXVq);
        eDif.SizeMode = PictureBoxSizeMode.StretchImage;
        eDif.TabIndex = Class13.jXVk;
        eDif.TabStop = false;
        jDi6.Anchor = AnchorStyles.None;
        jDi6.AutoSize = true;
        jDi6.Location = new Point(3, 0);
        jDi6.Name = Class13.qXVM;
        jDi6.Size = new Size(Class13.aXVu, Class13.QXVg);
        jDi6.TabIndex = Class13.AXV2;
        jDi6.Text = Class13.CXV3;
        vDix.Anchor = AnchorStyles.None;
        vDix.AutoSize = true;
        vDix.Location = new Point(Class13.FXVd, 0);
        vDix.Name = Class13.OXVH;
        vDix.Size = new Size(Class13.hXV4, Class13.KXV5);
        vDix.TabIndex = Class13.AXVs;
        vDix.Text = Class13.MXVZ;
        hDi9.Anchor = AnchorStyles.None;
        hDi9.AutoSize = true;
        hDi9.Location = new Point(Class13.iXVa, 0);
        hDi9.Name = Class13.BXVj;
        hDi9.Size = new Size(Class13.vXVz, Class13.RXOE);
        hDi9.TabIndex = Class13.EXOD;
        hDi9.Text = Class13.nXOX;
        yDic.Anchor = AnchorStyles.None;
        yDic.AutoSize = true;
        yDic.Location = new Point(Class13.mXOp, 0);
        yDic.Name = Class13.hXOS;
        yDic.Size = new Size(Class13.NXOh, Class13.xXOl);
        yDic.TabIndex = Class13.NXOG;
        yDic.Text = Class13.UXOb;
        JDiy.Anchor = AnchorStyles.None;
        JDiy.AutoSize = true;
        JDiy.Location = new Point(Class13.bXOv, 0);
        JDiy.Name = Class13.KXOo;
        JDiy.Size = new Size(Class13.JXOt, Class13.UXOV);
        JDiy.TabIndex = Class13.XXOO;
        JDiy.Text = Class13.mXOe;
        XDir.Anchor = AnchorStyles.None;
        XDir.AutoSize = true;
        XDir.Location = new Point(Class13.eXO8, Class13.NXOn);
        XDir.Name = Class13.rXOQ;
        XDir.Size = new Size(0, Class13.jXOF);
        XDir.TabIndex = Class13.NXOL;
        MDiq.Anchor = AnchorStyles.None;
        MDiq.AutoSize = true;
        MDiq.Location = new Point(Class13.BXOJ, Class13.rXO7);
        MDiq.Name = Class13.CXOP;
        MDiq.Size = new Size(0, Class13.CXOi);
        MDiq.TabIndex = Class13.YXOm;
        WDik.Anchor = AnchorStyles.None;
        WDik.AutoSize = true;
        WDik.Location = new Point(Class13.OXO0, Class13.xXOI);
        WDik.Name = Class13.SXOR;
        WDik.Size = new Size(0, Class13.eXOC);
        WDik.TabIndex = Class13.xXOK;
        iDiM.Anchor = AnchorStyles.None;
        iDiM.AutoSize = true;
        iDiM.Location = new Point(Class13.vXOU, Class13.fXOT);
        iDiM.Name = Class13.RXO1;
        iDiM.Size = new Size(0, Class13.RXOW);
        iDiM.TabIndex = Class13.aXOw;
        dDiu.Anchor = AnchorStyles.None;
        dDiu.BackColor = Color.DarkGray;
        dDiu.BackgroundImageLayout = ImageLayout.Center;
        dDiu.Image = (Image)componentResourceManager.GetObject(Class13.YXON);
        dDiu.Location = new Point(Class13.iXOY, Class13.fXOB);
        dDiu.Name = Class13.mXOA;
        dDiu.Size = new Size(Class13.UXOf, Class13.WXO6);
        dDiu.SizeMode = PictureBoxSizeMode.StretchImage;
        dDiu.TabIndex = Class13.TXOx;
        dDiu.TabStop = false;
        pDig.Anchor = AnchorStyles.None;
        pDig.BackColor = Color.DarkGray;
        pDig.BackgroundImageLayout = ImageLayout.Center;
        pDig.Image = (Image)componentResourceManager.GetObject(Class13.IXO9);
        pDig.Location = new Point(Class13.LXOc, Class13.lXOy);
        pDig.Name = Class13.bXOr;
        pDig.Size = new Size(Class13.VXOq, Class13.hXOk);
        pDig.SizeMode = PictureBoxSizeMode.StretchImage;
        pDig.TabIndex = Class13.EXOM;
        pDig.TabStop = false;
        eDi2.Anchor = AnchorStyles.None;
        eDi2.BackColor = Color.DarkGray;
        eDi2.BackgroundImageLayout = ImageLayout.Center;
        eDi2.Image = (Image)componentResourceManager.GetObject(Class13.AXOu);
        eDi2.Location = new Point(Class13.FXOg, Class13.BXO2);
        eDi2.Name = Class13.LXO3;
        eDi2.Size = new Size(Class13.JXOd, Class13.MXOH);
        eDi2.SizeMode = PictureBoxSizeMode.StretchImage;
        eDi2.TabIndex = Class13.vXO4;
        eDi2.TabStop = false;
        aDi3.Anchor = AnchorStyles.None;
        aDi3.BackColor = Color.DarkGray;
        aDi3.BackgroundImageLayout = ImageLayout.Center;
        aDi3.Image = (Image)componentResourceManager.GetObject(Class13.VXO5);
        aDi3.Location = new Point(Class13.dXOs, Class13.WXOZ);
        aDi3.Name = Class13.mXOa;
        aDi3.Size = new Size(Class13.FXOj, Class13.mXOz);
        aDi3.SizeMode = PictureBoxSizeMode.StretchImage;
        aDi3.TabIndex = Class13.dXeE;
        aDi3.TabStop = false;
        ODid.Anchor = AnchorStyles.None;
        ODid.BackColor = Color.DarkGray;
        ODid.BackgroundImageLayout = ImageLayout.Center;
        ODid.Image = (Image)componentResourceManager.GetObject(Class13.GXeD);
        ODid.Location = new Point(Class13.CXeX, Class13.MXep);
        ODid.Name = Class13.zXeS;
        ODid.Size = new Size(Class13.eXeh, Class13.eXel);
        ODid.SizeMode = PictureBoxSizeMode.StretchImage;
        ODid.TabIndex = Class13.zXeG;
        ODid.TabStop = false;
        PDiH.Anchor = AnchorStyles.None;
        PDiH.BackColor = Color.DarkGray;
        PDiH.BackgroundImageLayout = ImageLayout.Center;
        PDiH.Image = (Image)componentResourceManager.GetObject(Class13.vXeb);
        PDiH.Location = new Point(Class13.GXev, Class13.MXeo);
        PDiH.Name = Class13.MXet;
        PDiH.Size = new Size(Class13.LXeV, Class13.rXeO);
        PDiH.SizeMode = PictureBoxSizeMode.StretchImage;
        PDiH.TabIndex = Class13.DXee;
        PDiH.TabStop = false;
        EDi4.Location = new Point(Class13.uXe8, Class13.pXen);
        EDi4.Name = Class13.UXeQ;
        EDi4.Size = new Size(Class13.uXeF, Class13.YXeL);
        EDi4.TabIndex = Class13.oXeJ;
        EDi4.Text = Class13.sXe7;
        EDi4.UseVisualStyleBackColor = true;
        EDi4.Click += aDi8;
        WDis.ColumnCount = 5;
        WDis.ColumnStyles.Add(new ColumnStyle());
        WDis.ColumnStyles.Add(new ColumnStyle());
        WDis.ColumnStyles.Add(new ColumnStyle());
        WDis.ColumnStyles.Add(new ColumnStyle());
        WDis.ColumnStyles.Add(new ColumnStyle());
        WDis.Controls.Add(xDiZ, 2, 1);
        WDis.Controls.Add(ODia, 3, 1);
        WDis.Controls.Add(MDij, 4, 1);
        WDis.Controls.Add(YDiz, 2, 2);
        WDis.Controls.Add(aDmE, 3, 2);
        WDis.Controls.Add(sDmD, 4, 2);
        WDis.Controls.Add(XDmX, 3, 3);
        WDis.Controls.Add(MDmp, 4, 3);
        WDis.Controls.Add(hDmS, 3, 4);
        WDis.Controls.Add(MDmh, 4, 4);
        WDis.Controls.Add(GDml, 0, 0);
        WDis.Controls.Add(JDmG, 1, 0);
        WDis.Controls.Add(EDmb, 2, 0);
        WDis.Controls.Add(IDmv, 3, 0);
        WDis.Controls.Add(NDmo, 4, 0);
        WDis.Controls.Add(qDmt, 0, 1);
        WDis.Controls.Add(oDmV, 0, 2);
        WDis.Controls.Add(xDmO, 0, 3);
        WDis.Controls.Add(PDme, 0, 4);
        WDis.Controls.Add(bDm8, 1, 1);
        WDis.Controls.Add(oDmn, 1, 2);
        WDis.Controls.Add(EDmQ, 1, 3);
        WDis.Controls.Add(SDmF, 1, 4);
        WDis.Controls.Add(uDmL, 2, 3);
        WDis.Controls.Add(FDmJ, 2, 4);
        WDis.Location = new Point(Class13.EXeP, Class13.EXei);
        WDis.Name = Class13.wXem;
        WDis.RowCount = 5;
        WDis.RowStyles.Add(new RowStyle());
        WDis.RowStyles.Add(new RowStyle());
        WDis.RowStyles.Add(new RowStyle());
        WDis.RowStyles.Add(new RowStyle());
        WDis.RowStyles.Add(new RowStyle());
        WDis.RowStyles.Add(new RowStyle(SizeType.Absolute, Class13.nXe0));
        WDis.Size = new Size(Class13.MXeI, Class13.dXeR);
        WDis.TabIndex = Class13.LXeC;
        xDiZ.Anchor = AnchorStyles.None;
        xDiZ.BackColor = Color.DarkGray;
        xDiZ.BackgroundImageLayout = ImageLayout.Center;
        xDiZ.Image = (Image)componentResourceManager.GetObject(Class13.UXeK);
        xDiZ.Location = new Point(Class13.OXeU, Class13.sXeT);
        xDiZ.Name = Class13.xXe1;
        xDiZ.Size = new Size(Class13.sXeW, Class13.VXew);
        xDiZ.SizeMode = PictureBoxSizeMode.StretchImage;
        xDiZ.TabIndex = 3;
        xDiZ.TabStop = false;
        ODia.Anchor = AnchorStyles.None;
        ODia.BackColor = Color.DarkGray;
        ODia.BackgroundImageLayout = ImageLayout.Center;
        ODia.Image = (Image)componentResourceManager.GetObject(Class13.MXeN);
        ODia.Location = new Point(Class13.aXeY, Class13.pXeB);
        ODia.Name = Class13.YXeA;
        ODia.Size = new Size(Class13.oXef, Class13.XXe6);
        ODia.SizeMode = PictureBoxSizeMode.StretchImage;
        ODia.TabIndex = 4;
        ODia.TabStop = false;
        MDij.Anchor = AnchorStyles.None;
        MDij.BackColor = Color.DarkGray;
        MDij.BackgroundImageLayout = ImageLayout.Center;
        MDij.Image = (Image)componentResourceManager.GetObject(Class13.BXex);
        MDij.Location = new Point(Class13.AXe9, Class13.VXec);
        MDij.Name = Class13.dXey;
        MDij.Size = new Size(Class13.tXer, Class13.UXeq);
        MDij.SizeMode = PictureBoxSizeMode.StretchImage;
        MDij.TabIndex = 5;
        MDij.TabStop = false;
        YDiz.Anchor = AnchorStyles.None;
        YDiz.BackColor = Color.DarkGray;
        YDiz.BackgroundImageLayout = ImageLayout.Center;
        YDiz.Image = (Image)componentResourceManager.GetObject(Class13.CXek);
        YDiz.Location = new Point(Class13.VXeM, Class13.qXeu);
        YDiz.Name = Class13.SXeg;
        YDiz.Size = new Size(Class13.dXe2, Class13.UXe3);
        YDiz.SizeMode = PictureBoxSizeMode.StretchImage;
        YDiz.TabIndex = 6;
        YDiz.TabStop = false;
        aDmE.Anchor = AnchorStyles.None;
        aDmE.BackColor = Color.DarkGray;
        aDmE.BackgroundImageLayout = ImageLayout.Center;
        aDmE.Image = (Image)componentResourceManager.GetObject(Class13.cXed);
        aDmE.Location = new Point(Class13.wXeH, Class13.RXe4);
        aDmE.Name = Class13.gXe5;
        aDmE.Size = new Size(Class13.mXes, Class13.hXeZ);
        aDmE.SizeMode = PictureBoxSizeMode.StretchImage;
        aDmE.TabIndex = 7;
        aDmE.TabStop = false;
        sDmD.Anchor = AnchorStyles.None;
        sDmD.BackColor = Color.DarkGray;
        sDmD.BackgroundImageLayout = ImageLayout.Center;
        sDmD.Image = (Image)componentResourceManager.GetObject(Class13.QXea);
        sDmD.Location = new Point(Class13.DXej, Class13.sXez);
        sDmD.Name = Class13.JX8E;
        sDmD.Size = new Size(Class13.CX8D, Class13.SX8X);
        sDmD.SizeMode = PictureBoxSizeMode.StretchImage;
        sDmD.TabIndex = 8;
        sDmD.TabStop = false;
        XDmX.Anchor = AnchorStyles.None;
        XDmX.BackColor = Color.DarkGray;
        XDmX.BackgroundImageLayout = ImageLayout.Center;
        XDmX.Image = (Image)componentResourceManager.GetObject(Class13.DX8p);
        XDmX.Location = new Point(Class13.cX8S, Class13.RX8h);
        XDmX.Name = Class13.YX8l;
        XDmX.Size = new Size(Class13.WX8G, Class13.JX8b);
        XDmX.SizeMode = PictureBoxSizeMode.StretchImage;
        XDmX.TabIndex = Class13.sX8v;
        XDmX.TabStop = false;
        MDmp.Anchor = AnchorStyles.None;
        MDmp.BackColor = Color.DarkGray;
        MDmp.BackgroundImageLayout = ImageLayout.Center;
        MDmp.Image = (Image)componentResourceManager.GetObject(Class13.FX8o);
        MDmp.Location = new Point(Class13.KX8t, Class13.aX8V);
        MDmp.Name = Class13.bX8O;
        MDmp.Size = new Size(Class13.CX8e, Class13.RX88);
        MDmp.SizeMode = PictureBoxSizeMode.StretchImage;
        MDmp.TabIndex = Class13.AX8n;
        MDmp.TabStop = false;
        hDmS.Anchor = AnchorStyles.None;
        hDmS.BackColor = Color.DarkGray;
        hDmS.BackgroundImageLayout = ImageLayout.Center;
        hDmS.Image = (Image)componentResourceManager.GetObject(Class13.eX8Q);
        hDmS.Location = new Point(Class13.AX8F, Class13.oX8L);
        hDmS.Name = Class13.IX8J;
        hDmS.Size = new Size(Class13.DX87, Class13.OX8P);
        hDmS.SizeMode = PictureBoxSizeMode.StretchImage;
        hDmS.TabIndex = Class13.pX8i;
        hDmS.TabStop = false;
        MDmh.Anchor = AnchorStyles.None;
        MDmh.BackColor = Color.DarkGray;
        MDmh.BackgroundImageLayout = ImageLayout.Center;
        MDmh.Image = (Image)componentResourceManager.GetObject(Class13.wX8m);
        MDmh.Location = new Point(Class13.kX80, Class13.UX8I);
        MDmh.Name = Class13.XX8R;
        MDmh.Size = new Size(Class13.jX8C, Class13.qX8K);
        MDmh.SizeMode = PictureBoxSizeMode.StretchImage;
        MDmh.TabIndex = Class13.yX8U;
        MDmh.TabStop = false;
        GDml.Anchor = AnchorStyles.None;
        GDml.AutoSize = true;
        GDml.Location = new Point(3, 0);
        GDml.Name = Class13.hX8T;
        GDml.Size = new Size(Class13.IX81, Class13.RX8W);
        GDml.TabIndex = Class13.DX8w;
        GDml.Text = Class13.IX8N;
        JDmG.Anchor = AnchorStyles.None;
        JDmG.AutoSize = true;
        JDmG.Location = new Point(Class13.xX8Y, 0);
        JDmG.Name = Class13.HX8B;
        JDmG.Size = new Size(Class13.EX8A, Class13.pX8f);
        JDmG.TabIndex = Class13.XX86;
        JDmG.Text = Class13.EX8x;
        EDmb.Anchor = AnchorStyles.None;
        EDmb.AutoSize = true;
        EDmb.Location = new Point(Class13.IX89, 0);
        EDmb.Name = Class13.zX8c;
        EDmb.Size = new Size(Class13.jX8y, Class13.DX8r);
        EDmb.TabIndex = Class13.nX8q;
        EDmb.Text = Class13.GX8k;
        IDmv.Anchor = AnchorStyles.None;
        IDmv.AutoSize = true;
        IDmv.Location = new Point(Class13.rX8M, 0);
        IDmv.Name = Class13.IX8u;
        IDmv.Size = new Size(Class13.FX8g, Class13.yX82);
        IDmv.TabIndex = Class13.WX83;
        IDmv.Text = Class13.nX8d;
        NDmo.Anchor = AnchorStyles.None;
        NDmo.AutoSize = true;
        NDmo.Location = new Point(Class13.fX8H, 0);
        NDmo.Name = Class13.oX84;
        NDmo.Size = new Size(Class13.oX85, Class13.tX8s);
        NDmo.TabIndex = Class13.BX8Z;
        NDmo.Text = Class13.eX8a;
        qDmt.Anchor = AnchorStyles.None;
        qDmt.AutoSize = true;
        qDmt.Location = new Point(Class13.AX8j, Class13.bX8z);
        qDmt.Name = Class13.GXnE;
        qDmt.Size = new Size(0, Class13.PXnD);
        qDmt.TabIndex = Class13.YXnX;
        oDmV.Anchor = AnchorStyles.None;
        oDmV.AutoSize = true;
        oDmV.Location = new Point(Class13.lXnp, Class13.XXnS);
        oDmV.Name = Class13.qXnh;
        oDmV.Size = new Size(0, Class13.jXnl);
        oDmV.TabIndex = Class13.eXnG;
        xDmO.Anchor = AnchorStyles.None;
        xDmO.AutoSize = true;
        xDmO.Location = new Point(Class13.KXnb, Class13.RXnv);
        xDmO.Name = Class13.XXno;
        xDmO.Size = new Size(0, Class13.MXnt);
        xDmO.TabIndex = Class13.kXnV;
        PDme.Anchor = AnchorStyles.None;
        PDme.AutoSize = true;
        PDme.Location = new Point(Class13.yXnO, Class13.TXne);
        PDme.Name = Class13.IXn8;
        PDme.Size = new Size(0, Class13.qXnn);
        PDme.TabIndex = Class13.bXnQ;
        bDm8.Anchor = AnchorStyles.None;
        bDm8.BackColor = Color.DarkGray;
        bDm8.BackgroundImageLayout = ImageLayout.Center;
        bDm8.Image = (Image)componentResourceManager.GetObject(Class13.dXnF);
        bDm8.Location = new Point(Class13.XXnL, Class13.GXnJ);
        bDm8.Name = Class13.jXn7;
        bDm8.Size = new Size(Class13.CXnP, Class13.EXni);
        bDm8.SizeMode = PictureBoxSizeMode.StretchImage;
        bDm8.TabIndex = Class13.gXnm;
        bDm8.TabStop = false;
        oDmn.Anchor = AnchorStyles.None;
        oDmn.BackColor = Color.DarkGray;
        oDmn.BackgroundImageLayout = ImageLayout.Center;
        oDmn.Image = (Image)componentResourceManager.GetObject(Class13.UXn0);
        oDmn.Location = new Point(Class13.hXnI, Class13.HXnR);
        oDmn.Name = Class13.DXnC;
        oDmn.Size = new Size(Class13.HXnK, Class13.XXnU);
        oDmn.SizeMode = PictureBoxSizeMode.StretchImage;
        oDmn.TabIndex = Class13.jXnT;
        oDmn.TabStop = false;
        EDmQ.Anchor = AnchorStyles.None;
        EDmQ.BackColor = Color.DarkGray;
        EDmQ.BackgroundImageLayout = ImageLayout.Center;
        EDmQ.Image = (Image)componentResourceManager.GetObject(Class13.vXn1);
        EDmQ.Location = new Point(Class13.UXnW, Class13.rXnw);
        EDmQ.Name = Class13.FXnN;
        EDmQ.Size = new Size(Class13.tXnY, Class13.eXnB);
        EDmQ.SizeMode = PictureBoxSizeMode.StretchImage;
        EDmQ.TabIndex = Class13.wXnA;
        EDmQ.TabStop = false;
        SDmF.Anchor = AnchorStyles.None;
        SDmF.BackColor = Color.DarkGray;
        SDmF.BackgroundImageLayout = ImageLayout.Center;
        SDmF.Image = (Image)componentResourceManager.GetObject(Class13.MXnf);
        SDmF.Location = new Point(Class13.mXn6, Class13.nXnx);
        SDmF.Name = Class13.hXn9;
        SDmF.Size = new Size(Class13.tXnc, Class13.oXny);
        SDmF.SizeMode = PictureBoxSizeMode.StretchImage;
        SDmF.TabIndex = Class13.oXnr;
        SDmF.TabStop = false;
        uDmL.Anchor = AnchorStyles.None;
        uDmL.BackColor = Color.DarkGray;
        uDmL.BackgroundImageLayout = ImageLayout.Center;
        uDmL.Image = (Image)componentResourceManager.GetObject(Class13.dXnq);
        uDmL.Location = new Point(Class13.IXnk, Class13.xXnM);
        uDmL.Name = Class13.SXnu;
        uDmL.Size = new Size(Class13.EXng, Class13.NXn2);
        uDmL.SizeMode = PictureBoxSizeMode.StretchImage;
        uDmL.TabIndex = Class13.IXn3;
        uDmL.TabStop = false;
        FDmJ.Anchor = AnchorStyles.None;
        FDmJ.BackColor = Color.DarkGray;
        FDmJ.BackgroundImageLayout = ImageLayout.Center;
        FDmJ.Image = (Image)componentResourceManager.GetObject(Class13.iXnd);
        FDmJ.Location = new Point(Class13.YXnH, Class13.YXn4);
        FDmJ.Name = Class13.zXn5;
        FDmJ.Size = new Size(Class13.TXns, Class13.uXnZ);
        FDmJ.SizeMode = PictureBoxSizeMode.StretchImage;
        FDmJ.TabIndex = Class13.AXna;
        FDmJ.TabStop = false;
        base.AutoScaleDimensions = new SizeF(Class13.gXnj, Class13.BXnz);
        base.AutoScaleMode = AutoScaleMode.Font;
        base.ClientSize = new Size(Class13.eXQE, Class13.CXQD);
        base.Controls.Add(WDis);
        base.Controls.Add(EDi4);
        base.Controls.Add(JDiU);
        base.FormBorderStyle = FormBorderStyle.FixedSingle;
        base.Name = Class13.SXQX;
        base.ShowIcon = false;
        Text = Class13.bXQp;
        JDiU.ResumeLayout(performLayout: false);
        JDiU.PerformLayout();
        ((ISupportInitialize)DDiT).EndInit();
        ((ISupportInitialize)oDi1).EndInit();
        ((ISupportInitialize)cDi5).EndInit();
        ((ISupportInitialize)rDiW).EndInit();
        ((ISupportInitialize)HDiw).EndInit();
        ((ISupportInitialize)qDiN).EndInit();
        ((ISupportInitialize)sDiY).EndInit();
        ((ISupportInitialize)bDiB).EndInit();
        ((ISupportInitialize)UDiA).EndInit();
        ((ISupportInitialize)eDif).EndInit();
        ((ISupportInitialize)dDiu).EndInit();
        ((ISupportInitialize)pDig).EndInit();
        ((ISupportInitialize)eDi2).EndInit();
        ((ISupportInitialize)aDi3).EndInit();
        ((ISupportInitialize)ODid).EndInit();
        ((ISupportInitialize)PDiH).EndInit();
        WDis.ResumeLayout(performLayout: false);
        WDis.PerformLayout();
        ((ISupportInitialize)xDiZ).EndInit();
        ((ISupportInitialize)ODia).EndInit();
        ((ISupportInitialize)MDij).EndInit();
        ((ISupportInitialize)YDiz).EndInit();
        ((ISupportInitialize)aDmE).EndInit();
        ((ISupportInitialize)sDmD).EndInit();
        ((ISupportInitialize)XDmX).EndInit();
        ((ISupportInitialize)MDmp).EndInit();
        ((ISupportInitialize)hDmS).EndInit();
        ((ISupportInitialize)MDmh).EndInit();
        ((ISupportInitialize)bDm8).EndInit();
        ((ISupportInitialize)oDmn).EndInit();
        ((ISupportInitialize)EDmQ).EndInit();
        ((ISupportInitialize)SDmF).EndInit();
        ((ISupportInitialize)uDmL).EndInit();
        ((ISupportInitialize)FDmJ).EndInit();
        ResumeLayout(performLayout: false);
    }
}